https://doi.org/10.1002/aps3.11517

What is the “modified” CTAB protocol? Characterizing modifications to the CTAB DNA extraction protocol 什麼是“改良”CTAB 協議？表徵 CTAB DNA 提取協議的修改
​
​
. 2023 Jun 2;11(3):e11517. doi:
. 2023 年 6 月 2 日;11(3):e11517. doi: 10.1002/aps3.11517
Abstract  摘要

Cetyltrimethylammonium bromide (CTAB)–based methods are widely used to isolate DNA from plant tissues, but the unique chemical composition of secondary metabolites among plant species has necessitated optimization. Research articles often cite a “modified” CTAB protocol without explicitly stating how the protocol had been altered, creating non‐reproducible studies. Furthermore, the various modifications that have been applied to the CTAB protocol have not been rigorously reviewed and doing so could reveal optimization strategies across study systems. We surveyed the literature for modified CTAB protocols used for the isolation of plant DNA. We found that every stage of the CTAB protocol has been modified, and we summarized those modifications to provide recommendations for extraction optimization. Future genomic studies will rely on optimized CTAB protocols. Our review of the modifications that have been used, as well as the protocols we provide here, could better standardize DNA extractions, allowing for repeatable and transparent studies.
以十六烷基三甲基溴化銨（CTAB）為基礎的方法廣泛用於從植物組織中分離 DNA，但由於植物物種之間次級代謝物的獨特化學組成，需要進行優化。研究文章經常引用「修改過的」CTAB 協議，但未明確說明協議如何被更改，導致研究無法重現。此外，對 CTAB 協議進行的各種修改尚未被嚴格審查，這樣做可能揭示跨研究系統的優化策略。我們調查了文獻中用於分離植物 DNA 的修改過的 CTAB 協議。我們發現 CTAB 協議的每個階段都被修改過，並總結了這些修改以提供提取優化的建議。未來的基因組研究將依賴於優化的 CTAB 協議。我們對已使用的修改進行的審查，以及我們在此提供的協議，可能更好地標準化 DNA 提取，從而允許可重複和透明的研究。

Keywords: cell lysis, cetyltrimethylammonium bromide (CTAB), DNA extraction, high‐throughput sequencing, molecular biology, molecular systematics, plant genetics
關鍵詞：細胞裂解，十六烷基三甲基溴化銨（CTAB），DNA 提取，高通量測序，分子生物學，分子系統學，植物遺傳學

It was immediately clear at the beginning of the molecular DNA revolution that contemporary protocols for plant DNA extractions were inadequately slow, expensive, and low‐throughput, and that alternative methods were needed (Doyle and Doyle, 1990). Extractions that included the detergent cetyltrimethylammonium bromide (CTAB) seemingly resolved those issues, allowing for fast, inexpensive, and relatively high‐throughput DNA extractions that required only small amounts of input tissue (Doyle and Doyle, 1987). Although CTAB had been used to extract DNA from plants for over three decades prior (Dutta et al., 1953; Murray and Thompson, 1980; Saghai‐Maroof et al., 1984), its use was popularized by Jeff and Jane Doyle (Doyle and Doyle, 1987), who demonstrated its efficacy while outlining how it could be individually optimized for different species. Despite the utility of CTAB‐based extraction methods, extractions from some organisms still failed to produce pure, high‐molecular‐weight DNA (Varma et al., 2007).
在分子 DNA 革命初期，很明顯當時的植物 DNA 提取協議速度緩慢、成本高昂且通量低，需要替代方法（Doyle and Doyle, 1990）。包含十六烷基三甲基溴化銨（CTAB）的提取方法似乎解決了這些問題，允許快速、低成本且相對高通量的 DNA 提取，僅需少量的輸入組織（Doyle and Doyle, 1987）。儘管 CTAB 在此之前已被用於植物 DNA 提取超過三十年（Dutta et al., 1953; Murray and Thompson, 1980; Saghai‐Maroof et al., 1984），但其使用是由 Jeff 和 Jane Doyle 推廣的（Doyle and Doyle, 1987），他們展示了其效能並說明如何針對不同物種進行個別優化。儘管 CTAB 為基礎的提取方法具有實用性，但從某些生物體中提取仍無法產生純淨、高分子量的 DNA（Varma et al., 2007）。

Suboptimal DNA extractions are caused by the same anatomical and chemical properties that allow plants to survive in their environments. Rigid cell walls, for example, provide structural support but trap DNA within cells, and their polysaccharides can inhibit downstream molecular approaches, such as PCR amplification, ligation, and enzymatic reactions (Do and Adams, 1991; Pandey et al., 1996; Varma et al., 2007). In addition, the secondary metabolites that protect plants from environmental stresses (Pratyusha, 2022) and, in particular, herbivory are also reactive when tissues are macerated during DNA extractions. Numerous secondary metabolites are present within plant cells, including polysaccharides, phenolic compounds, anthocyanins, alkaloids, saponins, essential oils, and resins, but polysaccharides and phenolic compounds are particularly difficult to remove during the extraction process (Do and Adams, 1991; Wilson, 1997) because they coprecipitate with DNA (Scott and Playford, 1996; Sharma et al., 2002). The optimization of DNA extractions since Doyle and Doyle (1987) has centered on isolating DNA in the face of the substantial obstacles caused by the coprecipitation of polysaccharides and phenolic compounds.
次優的 DNA 提取是由於植物在其環境中生存的相同解剖和化學特性所造成的。例如，堅硬的細胞壁提供結構支持，但將 DNA 困在細胞內，其多醣類可能會抑制後續的分子方法，如 PCR 擴增、連接和酶反應（Do and Adams, 1991; Pandey et al., 1996; Varma et al., 2007）。此外，保護植物免受環境壓力（Pratyusha, 2022）尤其是草食性動物侵害的次級代謝物在組織於 DNA 提取過程中被磨碎時也會產生反應。 植物細胞中存在許多次級代謝物，包括多醣、酚類化合物、花青素、生物鹼、皂苷、精油和樹脂，但多醣和酚類化合物在提取過程中特別難以去除（Do 和 Adams, 1991; Wilson, 1997），因為它們會與 DNA 共沉澱（Scott 和 Playford, 1996; Sharma 等, 2002）。自 Doyle 和 Doyle（1987）以來，DNA 提取的優化一直集中在克服多醣和酚類化合物共沉澱所造成的重大障礙，以分離 DNA。

Over 8000 phenolic compounds have been described in plants, including simple phenols, phenolic acids, and polyphenols, among others (Pratyusha, 2022). When cells are disrupted, phenolic compounds are released from the vacuoles and freely undergo oxidative reactions (Pratyusha, 2022), which can either be catalyzed by oxidizing enzymes or occur non‐enzymatically (Loomis and Battaile, 1966). Lysates become discolored as they oxidize, even turning black in some reactions. During oxidation, phenolic compounds covalently bond with DNA, and these bonds cannot be broken with traditional extraction protocols (Loomis and Battaile, 1966; John, 1992; Varma et al., 2007; Abubakar et al., 2018). Consequently, the DNA–phenol complexes formed during oxidation are discarded during the cleaning process due to their high molecular weight (Japelaghi et al., 2011), ultimately yielding little to no DNA.
在植物中已描述超過 8000 種酚類化合物，包括簡單酚、酚酸和多酚等（Pratyusha, 2022）。當細胞被破壞時，酚類化合物從液泡中釋放出來，自由地進行氧化反應（Pratyusha, 2022），這些反應可以由氧化酶催化或非酶促進行（Loomis and Battaile, 1966）。裂解液在氧化過程中會變色，甚至在某些反應中變黑。在氧化過程中，酚類化合物與 DNA 共價結合，這些結合無法通過傳統的提取方法打破（Loomis and Battaile, 1966; John, 1992; Varma et al., 2007; Abubakar et al., 2018）。因此，氧化過程中形成的 DNA–酚複合物由於其高分子量，在清洗過程中被丟棄（Japelaghi et al., 2011），最終幾乎得不到 DNA。

Polysaccharide and DNA coprecipitation creates two major issues during DNA extractions. First, the reaction becomes viscous with the addition of alcohol, resulting in incorrect pipetted volumes. Second, and more importantly, polysaccharides inhibit downstream molecular reactions (Shioda and Murakami‐Murofushi, 1987; Pandey et al., 1996; Varma et al., 2007). Not all polysaccharides inhibit downstream approaches, however. Neutral polysaccharides are benign in restriction digestions, but acidic polysaccharides, such as carrageenan, gum ghatti, and others, inhibit restriction digests (Do and Adams, 1991).
多醣和 DNA 共沉澱在 DNA 提取過程中會造成兩個主要問題。首先，加入酒精後反應變得黏稠，導致移液體積不準確。其次，更重要的是，多醣會抑制後續的分子反應（Shioda 和 Murakami‐Murofushi, 1987; Pandey et al., 1996; Varma et al., 2007）。然而，並非所有多醣都會抑制後續的操作。中性多醣在限制性消化中是無害的，但酸性多醣，如卡拉膠、印度樹膠等，會抑制限制性消化（Do 和 Adams, 1991）。

Preventing polysaccharide and phenolic compound coprecipitation remains the greatest challenge during DNA extractions. DNA extractions received considerable attention near the end of the 20th century, when coprecipitates inhibited commonly used methods at the time, such as gene mapping, Southern blots, genetic fingerprinting, and Sanger sequencing for phylogenetic and population studies. Low yield and highly contaminated DNA extractions, however, are just as problematic today (as evidenced by other articles in this special issue; e.g., Jones et al., 2023; Xie et al., 2023) and will continue to play a prominent role in the future. Coprecipitates, such as polysaccharides and phenolic compounds, inhibit PCR amplification, ligation, and restriction digestion (Do and Adams, 1991; Fang et al., 1992; Pandey et al., 1996) and continue to be problematic for molecular studies. Commonly used genomic approaches, such as genomic library construction for high‐throughput sequencing, require ligation and PCR amplification that can be inhibited by coprecipitates. Gene quantification techniques, such as quantitative PCR, are also impeded by these contaminants (Demeke et al., 2009). Restriction site–associated DNA sequencing (RADseq), a commonly applied reduced representation genomic approach (Baird et al., 2008; Davey and Blaxter, 2010), requires restriction digestion. In RADseq experiments, impurities in the DNA extractions could inhibit enzymatic digestion, resulting in missing loci that could limit inferences of population structure and phylogenetic relationships (Leaché et al., 2015). Next‐generation sequencing approaches, such as Illumina's (San Diego, California, USA) sequencing by synthesis, utilize polymerases (Chen, 2014), which are inhibited by polysaccharides. The coprecipitation of phenolic compounds and polysaccharides might be a factor causing poor high‐throughput sequencing of some species or samples (e.g., Becklund and Ayers, 2022; Cohen and Schenk, 2022; Donoghue et al., 2022), but this hypothesis is yet to be tested. As biologists move toward long‐read genomic sequencing, our capacity to sequence kilobases of nucleotides will be limited by our ability to extract unfragmented and high‐quality DNA (Cerda et al., 2023; Kang et al., 2023; Xie et al., 2023). Optimizing the CTAB protocol to remove secondary metabolites is, therefore, imperative for the future of genomic studies.
防止多醣和酚類化合物共沉澱仍然是 DNA 提取過程中最大的挑戰。DNA 提取在 20 世紀末受到了相當大的關注，當時的共沉澱物抑制了當時常用的方法，如基因圖譜、Southern 印跡、基因指紋識別和 Sanger 測序，用於系統發育和群體研究。然而，低產量和高度污染的 DNA 提取在今天仍然同樣成問題（如本期特刊中的其他文章所證明；例如，Jones 等，2023；Xie 等，2023），並將在未來繼續發揮重要作用。共沉澱物，如多醣和酚類化合物，抑制 PCR 擴增、連接和限制性消化（Do 和 Adams，1991；Fang 等，1992；Pandey 等，1996），並繼續對分子研究造成問題。常用的基因組方法，如用於高通量測序的基因組文庫構建，需要連接和 PCR 擴增，而這些過程可能會被共沉澱物抑制。 基因定量技術，如定量 PCR，也受到這些污染物的阻礙（Demeke et al., 2009）。限制性位點相關 DNA 測序（RADseq）是一種常用的減少代表性基因組方法（Baird et al., 2008; Davey and Blaxter, 2010），需要進行限制性消化。在 RADseq 實驗中，DNA 提取中的雜質可能會抑制酶消化，導致缺失的基因座，這可能限制對群體結構和系統發育關係的推斷（Leaché et al., 2015）。新一代測序方法，如 Illumina（美國加利福尼亞州聖地牙哥）的合成測序，使用聚合酶（Chen, 2014），而聚合酶會被多醣類抑制。酚類化合物和多醣類的共沉澱可能是導致某些物種或樣本高通量測序效果不佳的因素（例如，Becklund and Ayers, 2022; Cohen and Schenk, 2022; Donoghue et al., 2022），但這一假設尚未得到驗證。 隨著生物學家逐步轉向長讀長基因組測序，我們對核苷酸千鹼基序列的測序能力將受到我們提取未碎片化和高質量 DNA 能力的限制（Cerda 等，2023；Kang 等，2023；Xie 等，2023）。因此，優化 CTAB 協議以去除次級代謝物對於基因組研究的未來至關重要。

The CTAB protocols popularized by Doyle and Doyle (1987, 1990) are currently the most commonly applied DNA extraction protocols, cited over 22,000 times (Google Scholar search on 11 August 2022; Doyle and Doyle, 2019). The authors recognized that plants vary greatly in their chemical compositions and obtaining pure, high‐molecular‐weight DNA is difficult in some species. Consequently, the authors included numerous alternative approaches to successfully extract DNA; we estimate they proposed 24 different ways, not including the varying of incubation times. Although the strength of the Doyle and Doyle (1987) protocol is its versatility, problems arise when research articles cite the paper as their approach but do not explicitly state the conditions under which they extracted DNA (even the lead author is guilty of making this error; Schenk and Hufford, 2011), or the authors state that a “modified” CTAB protocol was performed without detailing the ways in which it was modified. Such scenarios have created a critical problem because those studies are neither transparent nor reproducible, neglecting the fundamental tenets of research articles. Furthermore, the numerous modifications of the CTAB protocol have not been rigorously reviewed. Performing such a review will assist researchers with optimizing their extractions while simultaneously illuminating the conditions of the protocols that are poorly understood.
由 Doyle 和 Doyle（1987, 1990）普及的 CTAB 協議目前是最常用的 DNA 提取協議，被引用超過 22,000 次（截至 2022 年 8 月 11 日的 Google Scholar 搜索；Doyle 和 Doyle, 2019）。作者認識到植物的化學成分差異很大，獲得純淨的高分子量 DNA 在某些物種中是困難的。因此，作者包括了許多替代方法以成功提取 DNA；我們估計他們提出了 24 種不同的方法，不包括變更孵育時間。儘管 Doyle 和 Doyle（1987）協議的優勢在於其多功能性，但當研究文章引用該論文作為其方法卻未明確說明提取 DNA 的條件時（即使是主要作者也犯過這個錯誤；Schenk 和 Hufford, 2011），或者作者聲稱執行了“修改過的”CTAB 協議卻未詳細說明修改的方式時，問題就出現了。這樣的情況造成了一個關鍵問題，因為這些研究既不透明也不可重複，忽視了研究文章的基本原則。 此外，CTAB 協議的眾多修改尚未經過嚴格審查。進行這樣的審查將有助於研究人員優化他們的提取過程，同時闡明那些尚未被充分理解的協議條件。

In our review, we detail the ways in which the CTAB protocol has been modified for plant DNA extractions over the years. To meet this objective, we surveyed a subset of the literature for studies that focused on modifying the CTAB protocol and reported how extraction protocols have varied across those studies. We conclude by providing several protocols (Appendices [Link], [Link]; see Supporting Information with this article) and recommendations for researchers to ensure that future studies are transparent and reproducible.
在我們的審查中，我們詳細說明了多年來 CTAB 協議在植物 DNA 提取方面的修改方式。為了達成這一目標，我們調查了一部分文獻，這些文獻專注於修改 CTAB 協議，並報告了這些研究中提取協議的變化。我們最後提供了幾個協議（附錄 [Link], [Link]；請參閱本文的支持信息）和建議，以確保未來的研究透明且可重複。

DISCUSSION  討論

The modified CTAB protocol
修改過的 CTAB 協議

Through our literature review, we have determined that citing a “modified” CTAB extraction is almost meaningless given the extensive ways the protocol has been modified across studies. In addition to chemical additives to reduce polysaccharide and phenolic compound coprecipitation, the individual steps of the CTAB protocol also have been modified in many ways. Below, we review how researchers have modified the protocol and discuss the importance of those modifications. We recognize eight protocol steps that are applied during CTAB extractions (Figure 1): tissue preparation, suspension, lysis, isolation, cleaning, elution, secondary cleanup, and quantification. Most protocols, however, did not include all eight steps, and often the suspension and secondary cleanup were omitted.
通過我們的文獻回顧，我們確定引用「改良」的 CTAB 提取幾乎沒有意義，因為該協議在各項研究中已被廣泛修改。除了添加化學物質以減少多醣和酚類化合物的共沉澱外，CTAB 協議的各個步驟也被以多種方式修改。以下，我們回顧研究人員如何修改該協議並討論這些修改的重要性。我們識別出在 CTAB 提取過程中應用的八個協議步驟（圖 1）：組織準備、懸浮、裂解、分離、清洗、洗脫、二次清理和定量。然而，大多數協議並未包含所有八個步驟，且通常省略了懸浮和二次清理。

Figure 1.  圖 1.

Figure 1

Open in a new tab
在新標籤中打開
Eight steps of the CTAB extraction protocols, all of which have been modified by researchers across studies. The majority of studies excluded the suspension and secondary cleanup steps, which are denoted with asterisks. Areas in tubes shaded blue denote where the DNA is located and those shaded light gray represent the organic phase during the cleaning steps. The lysis step included the application of heat to facilitate cell and tissue lysis. The cleaning step often, but not always, involved precipitation of the DNA at freezing temperatures.
CTAB 提取協議的八個步驟，所有這些步驟在不同研究中都被研究人員修改過。大多數研究排除了懸浮和二次清理步驟，這些步驟用星號標示。試管中藍色陰影區域表示 DNA 所在位置，淺灰色陰影區域表示清理步驟中的有機相。裂解步驟包括應用熱量以促進細胞和組織的裂解。清理步驟通常（但不總是）涉及在冷凍溫度下沉澱 DNA。
Tissue preparation  組織準備

Both tissue selection and method of storage are vital to the success of DNA extractions. Freshly collected tissues that are frozen in liquid nitrogen tend to perform best (Doyle and Doyle, 1990), but extractions from tissues desiccated in silica gel also produce high‐molecular‐weight and pure DNA (Chase and Hills, 1991). A high‐salt CTAB solution has also been used as an alternative method to store leaf samples that can later be extracted (Rogstad, 1992; Štorchová et al., 2000), as has the use of ethanol storage (Johnson et al., 2023). The best tissues to use are young leaves, as greater yields and purity of DNA have been obtained from them compared to mature leaves, roots, fruits, and stems (Jobes et al., 1995; Japelaghi et al., 2011; Abubakar et al., 2018), although Rogers and Bendich (1985) determined that embryos produced the highest yields. Leaves that have experienced stress, such as herbivory, will likely have mounted a chemical defense that includes secondary metabolites (Usha Rani and Jyothsna, 2010) and should therefore be avoided, especially in groups with high concentrations of phenolic compounds.
組織選擇和儲存方法對於 DNA 提取的成功至關重要。新鮮採集的組織在液氮中冷凍通常表現最佳（Doyle 和 Doyle，1990），但從矽膠中乾燥的組織中提取的 DNA 也具有高分子量和純度（Chase 和 Hills，1991）。高鹽 CTAB 溶液也被用作儲存葉片樣本的替代方法，這些樣本可以在之後進行提取（Rogstad，1992；Štorchová等，2000），乙醇儲存也被使用（Johnson 等，2023）。最佳的組織是幼葉，因為與成熟葉、根、果實和莖相比，從中獲得的 DNA 產量和純度更高（Jobes 等，1995；Japelaghi 等，2011；Abubakar 等，2018），儘管 Rogers 和 Bendich（1985）認為胚胎產量最高。經歷過壓力的葉片，如被食草動物侵害，可能會啟動包括次級代謝物在內的化學防禦，因此應避免使用，特別是在含有高濃度酚類化合物的群體中。

Tissues from herbarium specimens have been successfully used in CTAB extractions (Cota‐Sánchez et al., 2006; Staats et al., 2011), including tissues as old as 204 years (Brewer et al., 2019). Extractions based on herbarium tissues are inferior to fresh or silica gel–preserved tissues because of DNA degradation and lower DNA yields (Ribeiro and Lovato, 2007; Staats et al., 2011). Carey et al. (2023) determined that herbarium tissues resulted in DNA extractions with significantly lower yields, more secondary contaminants, and shorter fragment lengths on average compared to silica gel–preserved tissues.
來自植物標本館的組織已成功用於 CTAB 提取（Cota‐Sánchez 等，2006；Staats 等，2011），包括長達 204 年的組織（Brewer 等，2019）。基於植物標本館組織的提取效果不如新鮮或矽膠保存的組織，因為 DNA 降解和 DNA 產量較低（Ribeiro 和 Lovato，2007；Staats 等，2011）。Carey 等（2023）確定植物標本館組織的 DNA 提取結果顯著較低的產量、更多的次要污染物，以及平均較短的片段長度，相較於矽膠保存的組織。

The amount of starting tissue used for DNA extractions varied substantially across protocols. For dried tissue, protocols used anywhere between 0.4–6000 mg (Syamkumar et al., 2003; Listyanto et al., 2021). Most protocols added 1000 mg of leaf tissue, which is similar to Doyle and Doyle (1987), who used 500–1500 mg. The ratio of tissue weight to buffer volume is likely an important, but overlooked, determinant of extraction success, which is discussed in greater detail below.
用於 DNA 提取的起始組織量在不同的協議中差異很大。對於乾燥組織，協議中使用的量介於 0.4–6000 毫克之間（Syamkumar et al., 2003; Listyanto et al., 2021）。大多數協議添加了 1000 毫克的葉組織，這與 Doyle 和 Doyle（1987）使用的 500–1500 毫克相似。組織重量與緩衝液體積的比例可能是一個重要但被忽視的提取成功因素，這在下面將進行更詳細的討論。

Suspension  懸浮液

An initial suspension buffer, which has sometimes been referred to as an extraction buffer (Li et al., 2001; Esfandani‐Bozchaloyi et al., 2019), was infrequently applied as a pretreatment or grinding buffer. Some protocols called for CTAB in the suspension buffer (Khanuja et al., 1999; Sharma et al., 2002), albeit at a higher concentration (10–20%) than what has typically been applied in a lysis buffer. The suspension buffers were often similar to the lysis buffers, and were just as variable in their contents, containing sorbitol, sucrose, Triton X‐100, polyvinylpyrrolidone (PVP), CTAB, Tris‐HCl, sodium bisulfate, EDTA, and β‐mercaptoethanol (Khanuja et al., 1999; Štorchová et al., 2000; Li et al., 2001; Esfandani‐Bozchaloyi et al., 2019). We also observed protocols that ground the tissues in pure β‐mercaptoethanol (Kim et al., 1997) or PVP (Sahu et al., 2012). The suspension step, when applied, often involved mechanical maceration followed by a short incubation (e.g., 15 min) at room temperature (Sharma et al., 2002), or no incubation, followed by centrifugation and transferral of the supernatant. The protocol of Esfandani‐Bozchaloyi et al. (2019) was quite different in applying a heated incubation during the suspension step and not during the lysis step.
初始懸浮緩衝液，有時被稱為提取緩衝液（Li et al., 2001; Esfandani‐Bozchaloyi et al., 2019），偶爾被用作預處理或研磨緩衝液。一些方案要求在懸浮緩衝液中加入 CTAB（Khanuja et al., 1999; Sharma et al., 2002），儘管其濃度（10–20%）高於通常在裂解緩衝液中使用的濃度。懸浮緩衝液通常與裂解緩衝液相似，其成分也同樣多變，包含山梨醇、蔗糖、Triton X‐100、聚乙烯吡咯烷酮（PVP）、CTAB、Tris‐HCl、亞硫酸鈉、EDTA 和β‐巰基乙醇（Khanuja et al., 1999; Štorchová et al., 2000; Li et al., 2001; Esfandani‐Bozchaloyi et al., 2019）。我們也觀察到一些方案將組織研磨在純β‐巰基乙醇（Kim et al., 1997）或 PVP（Sahu et al., 2012）中。當應用懸浮步驟時，通常涉及機械研磨，隨後在室溫下短暫孵育（例如 15 分鐘）（Sharma et al., 2002），或者不進行孵育，接著進行離心並轉移上清液。 Esfandani‐Bozchaloyi 等人（2019）的協議在懸浮步驟中應用了加熱孵育，而不是在裂解步驟中，這一點相當不同。

Lysis  裂解

The lysis step typically involved maceration of the tissues in a lysis buffer and then a heated incubation. We refer to a buffer as a lysis buffer only if it is incubated with heat. Most protocols macerated tissues in lysis buffer immediately after tissue preparation instead of using a suspension buffer. The main function of the lysis step is to disintegrate tissues, cells, and organelles to release their contents, and in particular, the DNA, from the protoplast, nucleus, and organelles. The lysis step, therefore, begins with maceration, which was usually done mechanically but can also be done enzymatically (Manen et al., 2005). Mechanical maceration often involved either bead mills or grinding with a mortar and pestle (Hale et al., 2020), and some approaches called for the addition of sterilized sand to facilitate grinding (Scott and Playford, 1996). Partially ground or dissolved tissues inhibit the extraction of high‐molecular‐weight DNA (Csaikl et al., 1998). Tissues were either ground frozen using liquid nitrogen, or desiccated tissues were ground dry and/or with a suspension or lysis buffer. Studies have concluded that mechanical maceration is superior to chemical maceration (Manen et al., 2005; Aboul‐Maaty and Oraby, 2019), and that grinding with liquid nitrogen to keep fresh tissues frozen resulted in better quality DNA, likely because of reduced reaction time of the phenolic compounds (Lodhi et al., 1994) or nuclease activity (Kasem et al., 2008). For the mechanical separation of tissues, bead mills produced higher‐molecular‐weight DNA than grinding tissues with a mortar and pestle (Drábková et al., 2002).
裂解步驟通常涉及將組織在裂解緩衝液中研磨，然後進行加熱孵育。我們僅在加熱孵育的情況下將緩衝液稱為裂解緩衝液。大多數方法在組織準備後立即將組織在裂解緩衝液中研磨，而不是使用懸浮緩衝液。裂解步驟的主要功能是分解組織、細胞和細胞器，以釋放其內容物，特別是從原生質體、細胞核和細胞器中釋放 DNA。因此，裂解步驟從研磨開始，這通常是機械完成的，但也可以通過酶進行（Manen et al., 2005）。機械研磨通常涉及使用珠磨機或研缽和杵進行研磨（Hale et al., 2020），有些方法要求加入滅菌砂以促進研磨（Scott and Playford, 1996）。部分研磨或溶解的組織會抑制高分子量 DNA 的提取（Csaikl et al., 1998）。組織要麼使用液氮冷凍研磨，要麼將乾燥的組織乾磨和/或與懸浮或裂解緩衝液一起研磨。 研究已經得出結論，機械研磨優於化學研磨（Manen et al., 2005; Aboul‐Maaty and Oraby, 2019），並且使用液氮研磨以保持新鮮組織冷凍，能夠產生更高質量的 DNA，這可能是因為酚類化合物的反應時間減少（Lodhi et al., 1994）或核酸酶活性降低（Kasem et al., 2008）。對於組織的機械分離，珠磨機產生的高分子量 DNA 比用研缽和杵研磨組織所得到的更高（Drábková et al., 2002）。

Lysis buffers included Tris, NaCl, EDTA, CTAB, and β‐mercaptoethanol, as well as many of the additives listed below. EDTA chelates Mg2+, which effectively inactivates nucleases, an important step in preventing DNA degradation during the extraction process (Rogers and Bendich, 1985; Puchooa, 2004). Protocols used different concentrations of CTAB. The Doyle and Doyle (1987) protocol called for a 2% CTAB concentration, which is the most common percentage, but modifications ranged between 1–4% (Saghai‐Maroof et al., 1984; Syamkumar et al., 2003). Using higher concentrations of CTAB reduces polysaccharides (Syamkumar et al., 2003), but CTAB is also a PCR inhibitor and can produce artificially high DNA concentration estimates when spectrophotometers are used (Demeke and Jenkins, 2010), necessitating the thorough removal of CTAB from the extractant during the cleaning step.
裂解緩衝液包含 Tris、NaCl、EDTA、CTAB 和β-巰基乙醇，以及下列許多添加劑。EDTA 螯合鎂離子，這能有效地使核酸酶失活，是在提取過程中防止 DNA 降解的重要步驟（Rogers 和 Bendich，1985；Puchooa，2004）。不同的方案使用了不同濃度的 CTAB。Doyle 和 Doyle（1987）方案要求 2%的 CTAB 濃度，這是最常見的比例，但修改範圍在 1-4%之間（Saghai‐Maroof 等，1984；Syamkumar 等，2003）。使用較高濃度的 CTAB 可以減少多醣（Syamkumar 等，2003），但 CTAB 也是 PCR 的抑制劑，並且在使用分光光度計時可能會產生虛高的 DNA 濃度估計（Demeke 和 Jenkins，2010），因此在清洗步驟中需要徹底去除提取物中的 CTAB。

The concentration of NaCl varied in lysis buffers. Using high concentrations of NaCl in the lysis buffer reduces polysaccharide coprecipitates in the extractant (Syamkumar et al., 2003; Abubakar et al., 2018), but as with high concentrations of CTAB, care must be taken to thoroughly clean the extraction as carryover can inhibit PCR amplification (Demeke and Jenkins, 2010). The Doyle and Doyle (1987) protocol called for 1.4 M NaCl, which is the most common concentration, but protocols ranged between 0.7–4 M (Saghai‐Maroof et al., 1984; Tel‐Zur et al., 1999).
在裂解緩衝液中，NaCl 的濃度有所不同。使用高濃度的 NaCl 在裂解緩衝液中可以減少多醣共沉澱物在提取物中的存在（Syamkumar 等，2003；Abubakar 等，2018），但如同使用高濃度的 CTAB 一樣，必須小心徹底清洗提取物，因為殘留物可能會抑制 PCR 擴增（Demeke 和 Jenkins，2010）。Doyle 和 Doyle（1987）的方法要求使用 1.4 M NaCl，這是最常見的濃度，但方法的範圍在 0.7–4 M 之間（Saghai‐Maroof 等，1984；Tel‐Zur 等，1999）。

The volume of lysis buffer applied across protocols ranged from 400–16,000 μL (Puchooa, 2004; Larridon et al., 2020), but on average most protocols used ≤2000 μL. To our knowledge, an experiment has not been published that determines the optimal ratio of the lysis buffer volume to tissue weight, evaluated by the purity and concentration of DNA during CTAB extractions. Murray and Thompson (1980) recommended 1 mL of buffer per 30–100 mg of dry weight powder. Puchooa (2004) did not detail their experimental design or what criterion was used, but recommended a 4:1 v/w ratio. We can assume that increased tissue amounts should require greater lysis buffer volume, but the ratio needs to be experimentally determined with explicit criteria based on DNA yield and purity across representative groups. In addition, greater buffer to tissue ratios might be necessary in plants with high concentrations of secondary metabolites, such as those that produce latex (Michiels et al., 2003). To extract under greater buffer to tissue ratios, some protocols advise splitting the lysate into two 1.5‐mL microcentrifuge tubes and then moving to the isolation step (Scott and Playford, 1996), but a smaller amount of starting tissue could alternatively be used to obtain a high buffer to tissue ratio. It is noteworthy that the Doyle and Doyle (1987) protocol applied 8000 μL of a lysis buffer in their reaction. The present‐day use of smaller volumes likely reflects the common usage of microcentrifugation, which allows only 1.5/2.0‐mL microcentrifuge tubes, as many laboratories simply do not have large‐volume centrifuges.
在不同的方案中，裂解緩衝液的使用量範圍從 400 到 16,000 μL 不等（Puchooa, 2004; Larridon et al., 2020），但平均而言，大多數方案使用的量不超過 2000 μL。據我們所知，目前尚未有實驗發表，能夠確定裂解緩衝液體積與組織重量的最佳比例，這是通過 CTAB 提取過程中 DNA 的純度和濃度來評估的。Murray 和 Thompson（1980）建議每 30–100 mg 的乾重粉末使用 1 mL 的緩衝液。Puchooa（2004）並未詳細說明其實驗設計或所使用的標準，但建議使用 4:1 的體積/重量比。我們可以假設，增加的組織量應該需要更多的裂解緩衝液，但這個比例需要通過實驗來確定，並基於代表性群體的 DNA 產量和純度的明確標準。此外，在含有高濃度次級代謝物的植物中，如那些產生乳膠的植物（Michiels et al., 2003），可能需要更高的緩衝液與組織比例。為了在更高的緩衝液與組織比例下進行提取，一些方案建議將裂解液分成兩份。5 毫升微量離心管，然後進行分離步驟（Scott 和 Playford，1996），但也可以使用較少量的起始組織以獲得較高的緩衝液與組織比例。值得注意的是，Doyle 和 Doyle（1987）的方法在反應中使用了 8000 微升的裂解緩衝液。現今使用較小體積可能反映了微量離心的普遍使用，因為許多實驗室根本沒有大容量的離心機，只能使用 1.5/2.0 毫升的微量離心管。

During the lysis step, the lysate is incubated above room temperature to facilitate tissue degradation and cell lysis. Incubation temperature and duration varied greatly among studies. Temperatures ranged between 55–70°C (Scott and Playford, 1996; Arruda et al., 2017), while Doyle and Doyle (1987) applied 60°C. The duration varied between 1–86,400 min (Rogers and Bendich, 1985; Larridon et al., 2020), which differed greatly from Doyle and Doyle's (1987) recommendation of 30–60 min. On average, studies used a temperature of around 60°C and incubated for 60 min. For shorter incubation times (≤30 min), preheating the lysis buffer is necessary (Doyle and Doyle, 1987). Carey et al. (2023) conducted experiments that explored a range of temperatures (50–65°C) and incubation times (1–24 h) and determined that on average cooler temperatures (~50–55°C) and shorter incubation times (1 h) resulted in slightly higher DNA yields, less coprecipitation, and longer DNA fragments, although not all differences in temperature and duration were significant.
在裂解步驟中，裂解液會在高於室溫的條件下孵育，以促進組織降解和細胞裂解。不同研究中的孵育溫度和時間差異很大。溫度範圍在 55–70°C 之間（Scott 和 Playford, 1996; Arruda 等, 2017），而 Doyle 和 Doyle (1987) 則使用 60°C。孵育時間從 1–86,400 分鐘不等（Rogers 和 Bendich, 1985; Larridon 等, 2020），這與 Doyle 和 Doyle (1987) 建議的 30–60 分鐘差異很大。平均而言，研究使用的溫度約為 60°C，孵育時間為 60 分鐘。對於較短的孵育時間（≤30 分鐘），需要預熱裂解緩衝液（Doyle 和 Doyle, 1987）。Carey 等 (2023) 進行了實驗，探索了不同的溫度範圍（50–65°C）和孵育時間（1–24 小時），並確定平均而言，較低的溫度（約 50–55°C）和較短的孵育時間（1 小時）會產生略高的 DNA 產量、較少的共沉澱以及較長的 DNA 片段，儘管並非所有溫度和時間的差異都是顯著的。

Mixing during incubation varied among protocols. Abubakar et al. (2018), for example, shook the tubes every 10 min during incubation, whereas Japelaghi et al. (2011) shook and vortexed every 5 min. Vortexing has been shown to provide some benefits but risks shearing the DNA (Sharma et al., 2000). Li et al. (2001) experimented with vortexing for zero, 20, 40, and 60 s after the lysis buffer was added and determined that 60 s produced the highest yield and that all three vortexing times resulted in higher yields than simply inverting, but the authors did not quantify the extent of DNA fragmentation in their experimental results.
在孵育期間的混合方式在不同的協議中有所不同。例如，Abubakar 等人（2018）在孵育期間每 10 分鐘搖動試管，而 Japelaghi 等人（2011）則每 5 分鐘搖動並震盪。震盪已被證明可以提供一些好處，但也有可能導致 DNA 斷裂（Sharma 等人，2000）。Li 等人（2001）在加入裂解緩衝液後，嘗試了震盪 0、20、40 和 60 秒，並確定 60 秒產生了最高的產量，且所有三個震盪時間的產量都高於僅僅倒置，但作者並未在實驗結果中量化 DNA 斷裂的程度。

Isolation  分離

During the isolation step, DNA is physically separated from all other cellular components that are produced in the lysate during the lysis step. Isolation is achieved in different ways. Recent studies applied a pre‐isolation step where the lysate was combined with a buffer and then filtered to remove large cellular debris (Jones et al., 2023; Xie et al., 2023), but the most common method was with 24:1 v/v chloroform–isoamyl alcohol (CIA). The volume of CIA should match that of the lysis buffer. Earlier CTAB protocols often included phenol, but it might not be necessary for plant tissues, and protocols have excluded it because of health risks (Varma et al., 2007). When the lysate is combined with CIA, the mixture separates into two phases, an upper aqueous and lower organic phase (Figure 1). The solubility of the chemicals in the lysate determines the phase in which they suspend. The lower organic phase includes proteins, lipids, and cellular debris, whereas the upper aqueous phase contains DNA, RNA, and polysaccharides; phenolic compounds are found in both phases. Some protocols (Japelaghi et al., 2011; Hale et al., 2020) call for briefly vortexing to mix the lysate with the CIA, but excessive vortexing should be avoided to prevent the DNA from shearing.
在分離步驟中，DNA 會從裂解步驟中產生的裂解液中的所有其他細胞成分中物理分離出來。分離可以通過不同的方法實現。最近的研究應用了預分離步驟，其中裂解液與緩衝液結合，然後過濾以去除大的細胞碎片（Jones et al., 2023; Xie et al., 2023），但最常見的方法是使用 24:1 v/v 氯仿-異戊醇（CIA）。CIA 的體積應與裂解緩衝液相匹配。早期的 CTAB 協議通常包括苯酚，但對於植物組織可能不是必需的，並且由於健康風險，協議已將其排除（Varma et al., 2007）。當裂解液與 CIA 結合時，混合物分離成兩個相，分別是上層水相和下層有機相（圖 1）。化學物質在裂解液中的溶解度決定了它們懸浮在哪個相中。下層有機相包括蛋白質、脂質和細胞碎片，而上層水相則包含 DNA、RNA 和多醣；酚類化合物在兩個相中都可以找到。 一些協議（Japelaghi et al., 2011; Hale et al., 2020）要求簡短地渦旋混合裂解液與 CIA，但應避免過度震盪，以防止 DNA 斷裂。

Centrifugation of the CIA and lysate mix facilitates the separation of the aqueous and organic phases and ranged between 8000–14,000 rpm for 0.5–30 min (Rogers and Bendich, 1985; Pirttilä et al., 2001; Cota‐Sánchez et al., 2006; Japelaghi et al., 2011). After centrifugation, the aqueous phase that includes the DNA is pipetted off and transferred into a new tube. One of the most critical steps of the extraction is pipetting the aqueous phase without disturbing the phase transition zone, as accidently doing so will greatly increase carryover.
CIA 和裂解液混合物的離心有助於水相和有機相的分離，轉速範圍在 8000–14,000 rpm 之間，時間為 0.5–30 分鐘（Rogers and Bendich, 1985; Pirttilä et al., 2001; Cota‐Sánchez et al., 2006; Japelaghi et al., 2011）。離心後，包含 DNA 的水相被移液取出並轉移到新的試管中。提取過程中最關鍵的步驟之一是移液取出水相時不干擾相轉換區，因為一旦不小心干擾，會大大增加交叉污染的風險。

The isolation step was often repeated when the aqueous phase was not clear (Porebski et al., 1997; Aboul‐Maaty and Oraby, 2019). A second, high‐concentration CTAB lysis buffer that ranged between 5× and 10× was included after isolation in some protocols (Murray and Thompson, 1980; Csaikl et al., 1998; Moreira and Oliveira, 2011). Sharma et al. (2002) recommended that colored pellets should be taken through the isolation and cleanup steps for up to three iterations. For extractions resulting in high concentrations of protein carryover, such as extractions from seeds, at least one extra CIA isolation should be used to remove proteins.
當水相不清晰時，通常會重複進行分離步驟（Porebski 等，1997；Aboul‐Maaty 和 Oraby，2019）。在某些方案中，分離後會加入濃度介於 5×到 10×之間的第二種高濃度 CTAB 裂解緩衝液（Murray 和 Thompson，1980；Csaikl 等，1998；Moreira 和 Oliveira，2011）。Sharma 等（2002）建議，帶有顏色的沉澱物應進行最多三次的分離和清理步驟。對於蛋白質殘留濃度較高的提取物，例如來自種子的提取物，至少應使用一次額外的 CIA 分離來去除蛋白質。

Cleaning  清理

The cleaning step could involve the use of commercially available DNA cleaning kits, but more often protocols used less expensive alcohols and sometimes salts. If alcohol and high‐concentration salts are used, the first step is to precipitate the DNA. Protocols either first precipitated the aqueous phase with isopropanol (chilled to –20°C or at room temperature), sometimes with the addition of salts (Aboul‐Maaty and Oraby, 2019), or –20°C EtOH was directly added to the aqueous phase in a separate tube. The earlier protocols that called for the use of a glass rod to remove the DNA after precipitation (e.g., Dutta et al., 1953; Bult et al., 1992) are no longer applied. In our protocols (Appendices S1–S4), the aqueous phase from the isolation stage was combined with 95% EtOH and precipitated overnight at –20°C. Alternative approaches included adding isopropanol and incubating at 25°C overnight, which resulted in lower yields but purer DNA (Michiels et al., 2003), or incubating at –20°C for 10–120 min (Štorchová et al., 2000; Abubakar et al., 2018). Other protocols advocated for the addition of salts with isopropanol to better precipitate the DNA. Tel‐Zur et al. (1999), for example, added 2/3 volume of sodium acetate and isopropanol and then immediately centrifuged, while Porebski et al. (1997) used 5 M NaCl with 95% EtOH chilled to –20°C, which precipitated at –20°C for 10 min to overnight. If high concentrations of salts are added, additional washes are necessary to prevent carryover (Pirttilä et al., 2001). After precipitation, the samples were centrifuged to create a pellet and the supernatant was removed (Figure 1). Some protocols recommended cold centrifugation (~4°C) to maintain the DNA precipitate during centrifugation (Drábková et al., 2002), but others presumably centrifuged at room temperature.
清洗步驟可能涉及使用市售的 DNA 清洗試劑盒，但更常見的是使用較便宜的酒精，有時還會使用鹽類。如果使用酒精和高濃度鹽類，第一步是沉澱 DNA。某些方法首先將水相與異丙醇（冷卻至–20°C 或室溫）沉澱，有時會加入鹽類（Aboul‐Maaty 和 Oraby，2019），或者直接在另一個試管中加入–20°C 的乙醇到水相。早期的方法要求在沉澱後使用玻璃棒移除 DNA（例如，Dutta 等，1953；Bult 等，1992），這些方法已不再使用。在我們的方法中（附錄 S1–S4），從分離階段獲得的水相與 95%乙醇混合，並在–20°C 下過夜沉澱。其他方法包括加入異丙醇並在 25°C 下過夜孵育，這樣會得到較低的產量但更純的 DNA（Michiels 等，2003），或者在–20°C 下孵育 10–120 分鐘（Štorchová等，2000；Abubakar 等，2018）。其他方法則建議加入鹽類與異丙醇以更好地沉澱 DNA。 例如，Tel‐Zur 等人（1999）加入 2/3 體積的醋酸鈉和異丙醇，然後立即進行離心，而 Porebski 等人（1997）使用 5 M NaCl 與冷卻至 –20°C 的 95% EtOH，並在 –20°C 下沉澱 10 分鐘至過夜。如果添加高濃度的鹽，則需要額外的清洗以防止殘留（Pirttilä 等人，2001）。沉澱後，樣品被離心以形成沉澱物，並移除上清液（圖 1）。一些方案建議在低溫下離心（約 4°C）以在離心過程中保持 DNA 沉澱（Drábková 等人，2002），但其他人可能在室溫下進行離心。

Extractions from herbarium specimens were precipitated for longer time periods, for example, up to two weeks at –20°C in 70% isopropanol (Staats et al., 2011). Hale et al. (2020) recommended precipitating DNA extracted from herbarium material in isopropanol at –20°C for 48 h to two weeks. We have not identified studies that experimentally determined the optimal alcohol, salt concentration, duration, or temperature during DNA precipitation, but experimentally optimizing this critical step could generate higher‐molecular‐weight and purer DNA extractions.
從植物標本中提取的樣本在-20°C 下以 70%異丙醇沉澱的時間較長，例如長達兩週（Staats et al., 2011）。Hale 等人（2020）建議將從植物標本中提取的 DNA 在-20°C 下以異丙醇沉澱 48 小時至兩週。我們尚未發現有研究實驗性地確定在 DNA 沉澱過程中最佳的酒精、鹽濃度、時間或溫度，但實驗性地優化這個關鍵步驟可能會產生更高分子量和更純的 DNA 提取物。

Most protocols incorporated two wash steps in 70–80% EtOH after the DNA was precipitated (Maguire et al., 1994; Štorchová et al., 2000), which is critical to remove the CTAB that is soluble in ~80% EtOH (Rogers and Bendich, 1985), as well as other salts. Washing in EtOH is preferred over isopropanol because solutes, such as sucrose and NaCl, can coprecipitate with isopropanol (Bult et al., 1992). Experimental studies have not been published to determine the best concentration of alcohol, but lower concentrations are likely important in high‐concentration‐salt protocols to reduce carryover. In some studies, the first wash was a higher concentration of alcohol than the second, and sometimes included additional salts to facilitate precipitation (Porebski et al., 1997). Xin and Chen (2012), for example, used Tris‐EDTA (TE) buffer in EtOH.
大多數方案在 DNA 沉澱後會加入兩次 70–80% EtOH 的洗滌步驟（Maguire 等，1994；Štorchová等，2000），這對於去除可溶於約 80% EtOH 的 CTAB 以及其他鹽類至關重要（Rogers 和 Bendich，1985）。與異丙醇相比，更偏好使用 EtOH 進行洗滌，因為像蔗糖和 NaCl 這樣的溶質可能會與異丙醇共沉澱（Bult 等，1992）。雖然尚未有實驗研究發表以確定最佳的酒精濃度，但在高濃度鹽方案中，較低的濃度可能對減少殘留很重要。在一些研究中，第一次洗滌使用的酒精濃度高於第二次，有時還會加入額外的鹽以促進沉澱（Porebski 等，1997）。例如，Xin 和 Chen（2012）在 EtOH 中使用 Tris‐EDTA（TE）緩衝液。

The final cleanup stage removes all traces of EtOH and/or isopropanol by removing the supernatant with a pipette and then either leaving the tubes open to allow the alcohol to evaporate at room temperature, or briefly applying low heat, sometimes under a vacuum. Removing all traces of alcohol is important as it inhibits PCR amplification (Demeke and Jenkins, 2010). Centrifuging with high force, for too long (Murray and Thompson, 1980), or overdrying the DNA pellet will result in damaged or low‐molecular‐weight DNA and prohibit the DNA pellet from dissolving in the elution buffer (see below).
最終的清理階段是通過使用移液器移除上清液來去除所有 EtOH 和/或異丙醇的痕跡，然後將試管打開以使酒精在室溫下蒸發，或者短暫施加低熱，有時在真空下進行。去除所有酒精痕跡很重要，因為它會抑制 PCR 擴增（Demeke 和 Jenkins，2010）。以過高的離心力或過長的時間進行離心（Murray 和 Thompson，1980），或過度乾燥 DNA 沉澱物，將導致 DNA 受損或分子量低，並且無法使 DNA 沉澱物溶解在洗脫緩衝液中（見下文）。

Elution  洗脫

The DNA pellet needs to be resuspended once it is dried. Protocols generally called for either the use of H2O (Moreira and Oliveira, 2011) or 1× TE, the latter of which is preferred to buffer the DNA. The elution volume ranged from 10–800 μL (Demeke and Adams, 1992; Štorchová et al., 2000), but 50–100 μL was most common. Some protocols heat the pellet in the elution buffer at 50–65°C for 5–120 min to resuspend the DNA (Rogers and Bendich, 1985; Aboul‐Maaty and Oraby, 2019), although lower temperatures are more prudent to prevent DNA fragmentation.
DNA 沉澱物在乾燥後需要重新懸浮。一般的操作流程要求使用 H₂O（Moreira 和 Oliveira，2011）或 1× TE，後者因能緩衝 DNA 而更受青睞。洗脫體積範圍從 10–800 μL（Demeke 和 Adams，1992；Štorchová等，2000），但最常見的是 50–100 μL。有些操作流程會將沉澱物在 50–65°C 的洗脫緩衝液中加熱 5–120 分鐘以重新懸浮 DNA（Rogers 和 Bendich，1985；Aboul‐Maaty 和 Oraby，2019），儘管較低的溫度更能防止 DNA 片段化。

Secondary cleanup  次級清理

Some protocols advocated for a post‐extraction secondary cleanup. Secondary cleanup is often applied with commercially available DNA cleaning kits (e.g., Demeke et al., 2009); however, some studies advocated for the use of chemical cleanups, such as cleaning with phenol and chloroform (Tel‐Zur et al., 1999; Michiels et al., 2003), magnetic beads (Larridon et al., 2020), or gel purification (Bult et al., 1992). Historically, ultracentrifugation with a CsCl gradient was employed for secondary cleanups (Doyle and Doyle, 1990; Wilkie et al., 1993), but that approach is no longer applied. If an extraction produced pure, high‐molecular‐weight DNA, a secondary cleanup, which is not mandatory, will only reduce DNA concentrations while wasting time and money.
有些方案倡導在提取後進行二次清理。二次清理通常使用市售的 DNA 清理套件（例如，Demeke 等，2009）；然而，一些研究提倡使用化學清理方法，如使用苯酚和氯仿清理（Tel‐Zur 等，1999；Michiels 等，2003）、磁珠（Larridon 等，2020）或凝膠純化（Bult 等，1992）。歷史上，使用 CsCl 梯度的超速離心法曾被用於二次清理（Doyle 和 Doyle，1990；Wilkie 等，1993），但該方法現已不再使用。如果提取產生了純淨的高分子量 DNA，則不強制要求的二次清理只會降低 DNA 濃度，同時浪費時間和金錢。

Quantification  定量

Four methods were commonly applied to quantify DNA: spectrophotometers, fluorometers, gel electrophoresis, and visualization of extractant color. Spectrophotometry, such as that applied with a NanoDrop (Thermo Fisher Scientific, Waltham, Massachusetts, USA), was the most common approach, even though DNA concentration estimation is problematic (Drábková et al., 2002). Despite the issues with quantifying DNA concentrations, NanoDrop can quantify coprecipitates in the extractant, including the ratio between the A260/A280 spectra, which measures the ratio of DNA to proteins, and the ratio between the A260/A230 spectra, which measures the ratio of DNA to contamination from phenolic compounds and polysaccharides (Varma et al., 2007). Carryover CTAB in the final extractant could increase the A260 nm absorbance readings, which will aberrantly inflate the estimated concentration of DNA (Doyle and Doyle, 1990; Wilkie et al., 1993). Consequently, a fluorometer that directly reads the concentration of DNA, such as the Qubit (Thermo Fisher Scientific) system, is preferred. Gel electrophoresis was often incorporated to determine the distribution of fragment lengths in the extractant, but interpreting concentrations from the banding pattern when they form continuous smears is challenging. A fragment analyzer provides a more rigorous approach to quantify the concentrations of fragment lengths compared to gel electrophoresis (Carey et al., 2023), as it quantifies concentrations and fragment lengths; however, it significantly increases the cost per sample compared to other quantification methods. The color of the extractant also indicates DNA quality (Varma et al., 2007); for example, pigmented extractants indicate phenol‐mediated oxidation (Esfandani‐Bozchaloyi et al., 2019). In our experience, darker extractants were unlikely to work in downstream applications, such as PCR; others have reported similar results (Esfandani‐Bozchaloyi et al., 2019).
四種方法常用於定量 DNA：分光光度計、螢光計、凝膠電泳和提取物顏色的可視化。分光光度法，例如使用 NanoDrop（Thermo Fisher Scientific, Waltham, Massachusetts, USA），是最常見的方法，儘管 DNA 濃度估算存在問題（Drábková等，2002）。儘管在定量 DNA 濃度方面存在問題，NanoDrop 可以量化提取物中的共沉澱物，包括 A 260 /A 280 光譜的比率，這測量 DNA 與蛋白質的比率，以及 A 260 /A 230 光譜的比率，這測量 DNA 與酚類化合物和多醣污染物的比率（Varma 等，2007）。最終提取物中殘留的 CTAB 可能會增加 A 260 nm 的吸光度讀數，這將異常地提高估計的 DNA 濃度（Doyle 和 Doyle，1990；Wilkie 等，1993）。因此，直接讀取 DNA 濃度的螢光計，例如 Qubit（Thermo Fisher Scientific）系統，更受青睞。 凝膠電泳常被用來確定提取物中片段長度的分佈，但當形成連續的條帶時，從條帶模式中解釋濃度是具有挑戰性的。相比於凝膠電泳，片段分析儀提供了一種更嚴謹的方法來量化片段長度的濃度（Carey et al., 2023），因為它可以量化濃度和片段長度；然而，與其他量化方法相比，它顯著增加了每個樣本的成本。 提取物的顏色也顯示了 DNA 的質量（Varma et al., 2007）；例如，帶色素的提取物表明酚介導的氧化（Esfandani‐Bozchaloyi et al., 2019）。根據我們的經驗，顏色較深的提取物在後續應用中，如 PCR，可能無法正常工作；其他研究也報告了類似的結果（Esfandani‐Bozchaloyi et al., 2019）。

Additives  添加劑

Chemical additives have been added to the suspension or lysis buffer to reduce polysaccharide coprecipitates and inhibit or remove phenols, and we outline the most commonly used additives below. Less frequently used additives have also been reported, but are not discussed here; these include ascorbic acid, bovine serum albumin, diethyldithiocarbamic acid, dithiothreitol, and sodium azide (see references in Puchooa, 2004; Varma et al., 2007). The four protocols provided in the Supporting Information include a basic CTAB protocol (Appendix S1) and three CTAB protocols that include the additives PVP (Appendix S2), sodium dodecyl sulphate (SDS) (Appendix S3), and sorbitol (Appendix S4). The CTAB, CTAB + PVP, and CTAB + SDS protocols apply six out of the eight steps—excluding the suspension and secondary cleanup steps. The CTAB + sorbitol protocol applies seven of the eight steps—excluding the secondary cleanup, but including a suspension step with a suspension buffer composed of sorbitol, Tris‐Cl, EDTA, and β‐mercaptoethanol.
化學添加劑已被添加到懸浮液或裂解緩衝液中，以減少多醣共沉澱並抑制或去除酚類，我們在下面概述了最常用的添加劑。較少使用的添加劑也有報導，但在此不作討論；這些包括抗壞血酸、牛血清白蛋白、二乙基二硫代氨基甲酸、二硫蘇糖醇和疊氮化鈉（參見 Puchooa, 2004; Varma et al., 2007 中的參考文獻）。附加信息中提供的四個協議包括一個基本的 CTAB 協議（附錄 S1）和三個包含添加劑 PVP（附錄 S2）、十二烷基硫酸鈉（SDS）（附錄 S3）和山梨醇（附錄 S4）的 CTAB 協議。CTAB、CTAB + PVP 和 CTAB + SDS 協議應用了八個步驟中的六個步驟——不包括懸浮和二次清理步驟。CTAB + 山梨醇協議應用了八個步驟中的七個步驟——不包括二次清理，但包括一個由山梨醇、Tris‐Cl、EDTA 和β‐巰基乙醇組成的懸浮緩衝液的懸浮步驟。

β‐mercaptoethanol  β‐巰基乙醇

The antioxidant β‐mercaptoethanol is applied in DNA extractions to prevent protein oxidation and denature proteins and was included in the Doyle and Doyle (1987) protocol. β‐mercaptoethanol is most commonly added to the CTAB lysis buffer. The concentrations of β‐mercaptoethanol ranged from 0% (Listyanto et al., 2021) to 5% (Arruda et al., 2017), but most protocols use 0.2–0.5%, which is similar to Doyle and Doyle's (1987) usage of 0.2%. The Fairlie and Pokorny protocol (cited in Larridon et al., 2020) recommended an increase of β‐mercaptoethanol from 0.2% to 0.4% when extracting DNA from herbarium specimens. Silva (2010) experimentally determined that higher concentrations of β‐mercaptoethanol, in their case 1–5%, resulted in cleaner and higher yields of DNA; however, any adverse effects of using high concentrations of β‐mercaptoethanol on downstream reactions are unknown, and further study is needed. β‐mercaptoethanol's toxicity and off‐putting smell has led many laboratories to omit its use in extractions (Listyanto et al., 2021); nevertheless, it does serve an important function in plant DNA extractions by degrading and removing proteins and preventing oxidation (Abubakar et al., 2018).
抗氧化劑β-巰基乙醇在 DNA 提取中被應用以防止蛋白質氧化並使蛋白質變性，並被包含在 Doyle 和 Doyle（1987）的協議中。β-巰基乙醇最常被添加到 CTAB 裂解緩衝液中。β-巰基乙醇的濃度範圍從 0%（Listyanto 等，2021）到 5%（Arruda 等，2017），但大多數協議使用 0.2–0.5%，這與 Doyle 和 Doyle（1987）使用的 0.2%相似。Fairlie 和 Pokorny 的協議（在 Larridon 等，2020 中引用）建議在從標本館標本中提取 DNA 時將β-巰基乙醇從 0.2%增加到 0.4%。Silva（2010）通過實驗確定較高濃度的β-巰基乙醇，在他們的情況下為 1–5%，導致更乾淨和更高產量的 DNA；然而，使用高濃度β-巰基乙醇對後續反應的任何不利影響尚不清楚，仍需進一步研究。 β-巰基乙醇的毒性和令人不快的氣味導致許多實驗室在提取中省略其使用（Listyanto 等，2021）；儘管如此，它在植物 DNA 提取中發揮著重要作用，通過降解和去除蛋白質並防止氧化（Abubakar 等，2018）。

Polyvinylpyrrolidone (PVP)
聚乙烯吡咯烷酮 （PVP）

PVP is an inert, high‐molecular‐weight polymer that forms hydrogen bonds with phenols, inhibiting their reactions and facilitating their removal (Loomis and Battaile, 1966; John, 1992). Compared to other additives, PVP is highly effective at removing phenols and preventing oxidation (Loomis and Battaile, 1966; Rogers and Bendich, 1985; Doyle and Doyle, 1990). Nazhad and Solouki (2008) determined that the addition of PVP increased final DNA concentrations. Compared to sorbitol and SDS additives, Carey et al. (2023) determined that the addition of PVP resulted in the highest yield with less coprecipitates. PVP is used at 1–2.5% in the lysis or suspension buffer (Cullings, 1992; Michiels et al., 2003; Sahu et al., 2012; Arruda et al., 2017). Some studies have used the molecularly similar polyvinylpolypyrrolidone (PVPP) as an alternative, but those extractions produced lower yields than those that used PVP (Lodhi et al., 1994; Porebski et al., 1997). Two forms of PVP were typically used, PVP‐40 (m.w. 40,000; e.g., Doyle and Doyle, 1990) and PVP‐10 (m.w. 10,000; e.g., Puchooa, 2004). Although PVP‐40 is more commonly applied, the use of lower‐molecular‐weight PVP‐10 resulted in higher DNA yield and did not coprecipitate with the DNA (Aljanabi et al., 1999; Puchooa, 2004; Varma et al., 2007). The PVP solution should be made fresh at the beginning of each extraction (John, 1992) and could require heat to dissolve (Kistler, 2012).
PVP 是一種惰性、高分子量的聚合物，能與酚類形成氫鍵，抑制其反應並促進其去除（Loomis 和 Battaile，1966；John，1992）。與其他添加劑相比，PVP 在去除酚類和防止氧化方面非常有效（Loomis 和 Battaile，1966；Rogers 和 Bendich，1985；Doyle 和 Doyle，1990）。Nazhad 和 Solouki（2008）發現添加 PVP 能提高最終的 DNA 濃度。與山梨醇和 SDS 添加劑相比，Carey 等人（2023）發現添加 PVP 能獲得最高的產量且共沉澱物較少。PVP 在裂解或懸浮緩衝液中的使用濃度為 1–2.5%（Cullings，1992；Michiels 等，2003；Sahu 等，2012；Arruda 等，2017）。一些研究使用了分子結構相似的聚乙烯吡咯烷酮（PVPP）作為替代，但這些提取的產量低於使用 PVP 的提取（Lodhi 等，1994；Porebski 等，1997）。通常使用兩種形式的 PVP，PVP‐40（分子量 40,000；例如，Doyle 和 Doyle，1990）和 PVP‐10（分子量 10,000；例如，Puchooa，2004）。 雖然 PVP-40 較常被使用，但使用較低分子量的 PVP-10 能夠獲得更高的 DNA 產量，且不會與 DNA 共沉澱（Aljanabi 等，1999；Puchooa，2004；Varma 等，2007）。PVP 溶液應在每次萃取開始時新鮮製備（John，1992），並可能需要加熱才能溶解（Kistler，2012）。

Proteinase K

The enzyme proteinase K inactivates proteins by breaking peptide bonds. Proteinase K denatures histones and prevents DNase‐ and RNase‐mediated oxidation of DNA or RNA, respectively (Varma et al., 2007). Therefore, although some protocols exclude it, proteinase K plays an important role during the extraction process and should be included in the lysis buffer. Some variation exists in the amount of proteinase K added, which has ranged from 1% of 1 mg/mL to 0.625% of 20 mg/mL in the lysis buffer (Porebski et al., 1997; Demeke et al., 2009).
蛋白酶 K 通過斷裂肽鍵來使蛋白質失活。蛋白酶 K 使組蛋白變性，並防止 DNase 和 RNase 分別介導的 DNA 或 RNA 氧化（Varma et al., 2007）。因此，儘管有些方案將其排除在外，但蛋白酶 K 在提取過程中扮演著重要角色，應該包含在裂解緩衝液中。添加的蛋白酶 K 量存在一些變化，在裂解緩衝液中的濃度範圍從 1 mg/mL 的 1%到 20 mg/mL 的 0.625%（Porebski et al., 1997; Demeke et al., 2009）。

RNase A

RNase breaks down RNA into ribonucleosides, inhibiting the coprecipitation of RNA with DNA during CTAB extractions (Zamboni et al., 2008). Some protocols do not use RNase A (Listyanto et al., 2021), but the presence of RNA could interfere with primer sites during PCR amplification (Jobes et al., 1995; Porebski et al., 1997). The application of RNase A occurred at different steps in the extraction protocol: before the EtOH wash step (Demeke et al., 2009) or after the elution stage (Abubakar et al., 2018). Studies varied in the amount of RNase used—from 0.5% of 34 μg/mL to 1% of 10 mg/mL (Cota‐Sánchez et al., 2006; Demeke et al., 2009)—with the latter concentration being more common than the former. Although RNA is degraded by RNase, the ribonucleosides are not removed from the extractant. Lithium chloride, which completely removes RNA and ribonucleosides (Pirttilä et al., 2001), has been used as an alternative to RNase (Ribeiro and Lovato, 2007).
RNase 會將 RNA 分解為核糖核苷，從而抑制 RNA 在 CTAB 萃取過程中與 DNA 共沉澱（Zamboni et al., 2008）。有些協議不使用 RNase A（Listyanto et al., 2021），但 RNA 的存在可能會在 PCR 擴增過程中干擾引物位點（Jobes et al., 1995; Porebski et al., 1997）。RNase A 的應用發生在萃取協議的不同步驟：在 EtOH 洗滌步驟之前（Demeke et al., 2009）或在洗脫階段之後（Abubakar et al., 2018）。研究中使用的 RNase 量各不相同——從 0.5% 的 34 μg/mL 到 1% 的 10 mg/mL（Cota‐Sánchez et al., 2006; Demeke et al., 2009）——後者的濃度比前者更為常見。雖然 RNA 被 RNase 降解，但核糖核苷並未從萃取物中移除。氯化鋰可以完全去除 RNA 和核糖核苷（Pirttilä et al., 2001），已被用作 RNase 的替代品（Ribeiro and Lovato, 2007）。

Salts  鹽類

High concentrations of salts reduce the concentration of polysaccharides in the extractant (Fang et al., 1992; Varma et al., 2007; Abubakar et al., 2018), increasing the purity of the DNA in the extractant (Scobeyeva et al., 2018). Fang et al. (1992) determined that 1 M NaCl was effective at removing polysaccharides in some groups, but tissues that contained high polysaccharide concentrations required 1.5 to 2.0 M. One study increased concentrations to 6 M NaCl (Aljanabi and Martinez, 1997). High salt concentrations, however, are difficult to remove from the final extractant, and they can inhibit downstream applications, such as PCR amplification (Demeke and Jenkins, 2010). Most protocols called for sodium chloride, but potassium acetate, sodium acetate, and sodium metabisulfite have also been included (Aljanabi et al., 1999; Pirttilä et al., 2001; Scobeyeva et al., 2018).
高濃度的鹽類可以降低抽提劑中多醣的濃度（Fang et al., 1992; Varma et al., 2007; Abubakar et al., 2018），從而提高抽提劑中 DNA 的純度（Scobeyeva et al., 2018）。Fang et al.（1992）確定 1 M NaCl 在某些組別中有效去除多醣，但對於含有高濃度多醣的組織則需要 1.5 到 2.0 M。有一項研究將濃度提高到 6 M NaCl（Aljanabi and Martinez, 1997）。然而，高鹽濃度難以從最終的抽提劑中去除，並且可能抑制後續應用，如 PCR 擴增（Demeke and Jenkins, 2010）。大多數方案使用氯化鈉，但也包括醋酸鉀、醋酸鈉和偏亞硫酸鈉（Aljanabi et al., 1999; Pirttilä et al., 2001; Scobeyeva et al., 2018）。

Sarkosyl

Sarkosyl is an amphiphilic detergent. In groups with high polysaccharide concentrations, such as Cactaceae, the use of sarkosyl might be vital to remove polysaccharides from the extractant (Tel‐Zur et al., 1999; Sharma et al., 2002). For polysaccharide removal, a 5% sarkosyl solution has been added to the lysis buffer as 10–20% of the total lysis buffer volume (Scott and Playford, 1996; Li et al., 2001).
Sarkosyl 是一種兩性界面活性劑。在多醣濃度高的群體中，例如仙人掌科，使用 sarkosyl 可能對於從提取物中去除多醣至關重要（Tel‐Zur 等，1999；Sharma 等，2002）。為了去除多醣，已在裂解緩衝液中加入 5% 的 sarkosyl 溶液，佔總裂解緩衝液體積的 10–20%（Scott 和 Playford，1996；Li 等，2001）。

Sodium dodecyl sulphate (SDS)
十二烷基硫酸鈉 (SDS)

SDS is another amphiphilic detergent that breaks down cells and denatures proteins (Kasem et al., 2008). SDS forms complexes with proteins and polysaccharides (Ramachandran et al., 2022), allowing the high‐molecular‐weight complexes to be easily removed. Ramachandran et al. (2022) determined that an addition of 5% SDS to a CTAB buffer outperformed other CTAB protocols that did not include it, but the extractants were not as pure because of carryover. Carey et al. (2023) also determined that the addition of SDS resulted in high carryover, but the DNA yield was not as high as a protocol that included only CTAB or CTAB + PVP. SDS at high concentrations can potentially shear the DNA (Jobes et al., 1995), but the extent of fragmentation has not been experimentally quantified. Most studies that include SDS do so in the lysis or suspension buffer at lower concentrations. Kotchoni et al. (2011), for example, recommended an addition of 1% SDS in the buffer from a 10% w/v stock solution when extracting DNA from Arabidopsis Heynh.
SDS 是另一種兩性界面活性劑，可以分解細胞並使蛋白質變性（Kasem et al., 2008）。SDS 與蛋白質和多醣形成複合物（Ramachandran et al., 2022），使高分子量的複合物易於去除。Ramachandran 等人（2022）發現，在 CTAB 緩衝液中添加 5% 的 SDS 比不包含 SDS 的其他 CTAB 協議效果更好，但由於殘留物，提取物的純度不高。Carey 等人（2023）也發現添加 SDS 會導致高殘留，但 DNA 產量不如僅包含 CTAB 或 CTAB + PVP 的協議高。高濃度的 SDS 可能會剪切 DNA（Jobes et al., 1995），但碎片化的程度尚未經過實驗量化。大多數包含 SDS 的研究是在低濃度的裂解或懸浮緩衝液中進行的。例如，Kotchoni 等人（2011）建議在從阿拉伯芥中提取 DNA 時，在緩衝液中添加 1% 的 SDS，該 SDS 來自 10% w/v 的儲備溶液。

Sorbitol  山梨醇

Sorbitol is a sugar alcohol that acts as a reducing agent and, at high concentrations, inhibits oxidation from polyphenols (Stein, 1993; Kasem et al., 2008). Sorbitol was first used by Scott and Playford (1996), and its success at reducing oxidation during the extraction has led to its application in other labs (Štorchová et al., 2000). Approximately 0.35 M sorbitol is typically applied in studies (Drábková et al., 2002), usually in a suspension buffer (Štorchová et al., 2000). Li et al. (2001) determined that the addition of sorbitol followed by vortexing increased DNA yield. A study by Carey et al. (2023) determined that sorbitol had higher contamination and lower yield than extractions with CTAB only or CTAB + PVP, but it had the largest average fragment size, which might make it appealing for long‐read sequencing.
山梨醇是一種糖醇，具有還原劑的作用，在高濃度下可抑制多酚的氧化（Stein, 1993; Kasem et al., 2008）。山梨醇最早由 Scott 和 Playford（1996）使用，其在提取過程中減少氧化的成功經驗使其在其他實驗室中得到應用（Štorchová et al., 2000）。通常在研究中應用約 0.35 M 的山梨醇（Drábková et al., 2002），通常是在懸浮緩衝液中（Štorchová et al., 2000）。Li 等人（2001）發現，加入山梨醇後進行渦旋混合可以提高 DNA 的產量。Carey 等人（2023）的研究發現，山梨醇的污染較高且產量低於僅使用 CTAB 或 CTAB + PVP 的提取，但其平均片段大小最大，這可能使其對於長讀序列測序具有吸引力。

Alternatives to CTAB  CTAB 的替代方案

CTAB is not the only method for the isolation of DNA from plants. Numerous commercial kits promise rapid extractions that result in high‐purity DNA. However, in all but one study that we came across (albeit with a modified protocol, Drábková et al., 2002), CTAB outperformed commercially available DNA extraction kits in generating greater yields, and in most cases, higher‐quality DNA. CTAB performed better than DNeasy Plant Mini Kit (Qiagen, Valencia, California, USA), DNP Kit (CinnaGen, Tehran, Iran), NucleoSpin Plant II (Machery‐Nagel, Düren, Germany), GeNei (Genei Laboratories, Peenya, India), and Wizard Resin (Promega, Madison, Wisconsin, USA) (Michiels et al., 2003; Demeke et al., 2009; Sahu et al., 2012; Abubakar et al., 2018; Esfandani‐Bozchaloyi et al., 2019). The advantage of the CTAB protocol over commercial kits is that it produces higher DNA yield and quality and each extraction is less expensive (Hale et al., 2020).
CTAB 並不是從植物中分離 DNA 的唯一方法。許多商業試劑盒承諾能快速提取出高純度的 DNA。然而，除了我們發現的一項研究（儘管使用了修改過的協議，Drábková等，2002 年），CTAB 在產生更高產量和在大多數情況下更高質量的 DNA 方面，表現優於市售的 DNA 提取試劑盒。CTAB 的表現優於 DNeasy Plant Mini Kit（Qiagen，美國加利福尼亞州瓦倫西亞）、DNP Kit（CinnaGen，伊朗德黑蘭）、NucleoSpin Plant II（Machery‐Nagel，德國杜倫）、GeNei（Genei Laboratories，印度 Peenya）和 Wizard Resin（Promega，美國威斯康辛州麥迪遜）（Michiels 等，2003 年；Demeke 等，2009 年；Sahu 等，2012 年；Abubakar 等，2018 年；Esfandani‐Bozchaloyi 等，2019 年）。CTAB 協議相較於商業試劑盒的優勢在於它能產生更高的 DNA 產量和質量，而且每次提取的成本更低（Hale 等，2020 年）。

Non‐commercial protocols that do not include CTAB have successfully extracted high‐quality, high‐molecular‐weight DNA, including those based on PVP (Guillemaut and Maréchal‐Drouard, 1992; Jobes et al., 1995; Ribeiro and Lovato, 2007), sorbitol (Scott and Playford, 1996; Ribeiro and Lovato, 2007), and SDS (Dellaporta et al., 1983; Jobes et al., 1995; Sharma et al., 2000; Hosaka, 2004; Ribeiro and Lovato, 2007; El Maaiden et al., 2019). In a study that evaluated the above methods in the tropical genus Dalbergia L.f. (Fabaceae), Ribeiro and Lovato (2007) determined the PVP‐only protocol of Jobes et al. (1995) and a CTAB protocol outperformed the others, whereas Csaikl et al. (1998) determined that two different CTAB protocols outperformed the SDS‐only protocols. An alternative method based on diethyldithiocarbamic acid was shown to be effective in the phenolic‐rich Theobroma cacao L. (Couch and Fritz, 1990), but the study did not include a comparison to CTAB. Enzymatic reactions applying a variety of enzymes that break down tissues and cells (e.g., cellulase, pectinase, glycosidase) are another approach that could also facilitate DNA extraction automation (Manen et al., 2005); however, enzymatic approaches require significant preparation and were not commonly applied. In ancient DNA samples, the use of N‐phenacylthiazolium bromide resulted in high‐quality extractions in Cucurbitaceae fruits (Kistler, 2012) and other degraded material (Bernardo et al., 2005).
不含 CTAB 的非商業化方案已成功提取出高品質、高分子量的 DNA，包括基於 PVP 的方案（Guillemaut 和 Maréchal‐Drouard, 1992; Jobes 等, 1995; Ribeiro 和 Lovato, 2007）、山梨醇的方案（Scott 和 Playford, 1996; Ribeiro 和 Lovato, 2007）以及 SDS 的方案（Dellaporta 等, 1983; Jobes 等, 1995; Sharma 等, 2000; Hosaka, 2004; Ribeiro 和 Lovato, 2007; El Maaiden 等, 2019）。在一項評估上述方法於熱帶屬 Dalbergia L.f.（Fabaceae）中的研究中，Ribeiro 和 Lovato（2007）確定 Jobes 等（1995）的僅 PVP 方案和一個 CTAB 方案表現優於其他方案，而 Csaikl 等（1998）則確定兩個不同的 CTAB 方案表現優於僅 SDS 方案。基於二乙基二硫代氨基甲酸的替代方法在富含酚類的 Theobroma cacao L.中被證明有效（Couch 和 Fritz, 1990），但該研究未包含與 CTAB 的比較。 使用各種酶來分解組織和細胞（例如，纖維素酶、果膠酶、糖苷酶）的酶促反應是另一種可以促進 DNA 提取自動化的方法（Manen et al., 2005）；然而，酶促方法需要大量的準備工作，因此並不常用。 在古代 DNA 樣本中，使用 N‐phenacylthiazolium bromide 在葫蘆科水果（Kistler,2012）和其他退化材料中（Bernardo et al., 2005）獲得了高品質的提取結果。

Recommendations and future directions
建議與未來方向

Properly cited DNA extraction protocols that explicitly state how they were modified are paramount (e.g., Demeke et al., 2009). Rather than stating “we extracted DNA using a modified CTAB protocol (Doyle and Doyle, 1987),” we should provide specific language, for example: “we extracted DNA with the Doyle and Doyle (1987) protocol except we repeated the isolation step twice.” This alternative is more informative and allows for the study to be reproducible, while remaining concise. Protocols with several modifications should be included in the supplemental materials, as we have done here (Appendices [Link], [Link]). As a community, we must do better to accurately report our experimental procedures and require our colleagues do the same during peer review.
正確引用明確說明如何修改的 DNA 提取方法是至關重要的（例如，Demeke 等，2009）。與其說「我們使用修改過的 CTAB 方法提取 DNA（Doyle 和 Doyle，1987）」，我們應該提供具體的說法，例如：「我們使用 Doyle 和 Doyle（1987）的方法提取 DNA，但重複了兩次分離步驟。」這種替代方式更具資訊性，並且能夠使研究具有可重複性，同時保持簡潔。具有多項修改的方案應包含在補充材料中，就像我們在此處所做的那樣（附錄[連結]，[連結]）。作為一個社群，我們必須更好地準確報告我們的實驗程序，並要求我們的同事在同行評審中也這樣做。

Although CTAB remains one of the most common extraction methods, it is still relatively low‐throughput. A recent study attempted to create a high‐throughput CTAB‐based protocol with some success (Xin and Chen, 2012), although it is not commonly applied. The Xin and Chen (2012) approach was notable in incorporating magnetic beads for cleaning an entire 96‐well plate; however, the need for a high‐throughput extraction protocol remains.
儘管 CTAB 仍然是最常用的提取方法之一，但其通量相對較低。最近的一項研究嘗試創建一種基於 CTAB 的高通量協議，並取得了一些成功（Xin 和 Chen，2012），儘管尚未普遍應用。Xin 和 Chen（2012）的方法值得注意的是其在清洗整個 96 孔板時引入了磁珠；然而，對於高通量提取協議的需求依然存在。

Additional research is needed to further explore how to best optimize CTAB DNA extractions. Those studies need to apply explicit criteria to evaluate optimization to address remaining issues, such as the presence of secondary metabolites, DNA yield, and average DNA fragment lengths. In particular, studies are needed to investigate the optimal tissue to buffer ratio, concentration of β‐mercaptoethanol, vortex duration (quantified with average DNA fragment length), precipitation duration, precipitation temperature, concentrations and forms of alcohol and associated salts during precipitation, alcohol concentrations during washing, and secondary metabolite inhibition on library construction and next‐generation sequencing (e.g., sequencing by synthesis). Although a universal extraction protocol still remains unlikely, optimization experiments can improve our ability to achieve better extractions across plant groups.
需要進一步研究以探索如何最佳化 CTAB DNA 提取方法。這些研究需要應用明確的標準來評估優化，以解決剩餘問題，例如次級代謝物的存在、DNA 產量和平均 DNA 片段長度。特別是，需要研究最佳的組織與緩衝液比例、β‐巰基乙醇的濃度、震盪時間（以平均 DNA 片段長度量化）、沉澱時間、沉澱溫度、沉澱過程中酒精和相關鹽類的濃度和形式、洗滌過程中的酒精濃度，以及次級代謝物對文庫構建和下一代測序（例如，合成測序）的抑制作用。儘管一個通用的提取方案仍不太可能實現，但優化實驗可以提高我們在不同植物群中獲得更好提取效果的能力。

AUTHOR CONTRIBUTIONS  作者貢獻

The study was envisioned and designed by L.E.B. and J.J.S., and the manuscript was written by J.J.S., L.E.B., S.J.C., and P.P.F. All authors approved the final version of the manuscript.
本研究由 L.E.B.和 J.J.S.構思和設計，手稿由 J.J.S.、L.E.B.、S.J.C.和 P.P.F.撰寫。所有作者均批准了手稿的最終版本。

Supporting information  支持資訊

Appendix S1. Total genomic DNA extraction from plant tissue using CTAB.
附錄 S1. 使用 CTAB 從植物組織中提取總基因組 DNA。

Appendix S2. Total genomic DNA extraction from plant tissue using CTAB + PVP.
附錄 S2. 使用 CTAB + PVP 從植物組織中提取總基因組 DNA。

Appendix S3. Total genomic DNA extraction from plant tissue using CTAB + SDS.
附錄 S3. 使用 CTAB + SDS 從植物組織中提取總基因組 DNA。

Appendix S4. Total genomic DNA extraction from plant tissue using CTAB + sorbitol.

ACKNOWLEDGMENTS

The authors thank Ohio University College of Arts and Sciences for funding an Internship Grant, the laboratories who sent us their protocols (Tina Ayers [Northern Arizona University], Jeff and Jane Doyle [Cornell University], Matthew Johnson [Texas Tech University], Laura Lagomarsino [Louisiana State University], and K. Marlowe [USDA]), labs that posted their protocols online (Kalisz lab [University of Tennessee, Knoxville] and Soltis lab [University of Florida]), and two anonymous reviewers for their thoughtful comments. This work was funded in part by a National Science Foundation grant (DEB award 2117446) to J.J.S.

Schenk, J. J. , L. E. Becklund , S. J. Carey , and P. P. Fabre . 2023. What is the “modified” CTAB protocol? Characterizing modifications to the CTAB DNA extraction protocol. Applications in Plant Sciences 11(3): e11517. 10.1002/aps3.11517

This article is part of the special issue “Emerging Methods in Botanical DNA/RNA Extraction.”

REFERENCES

Aboul‐Maaty, N. A.‐F. , and Oraby H. A.‐S.. 2019. Extraction of high‐quality genomic DNA from different plant orders applying a modified CTAB‐based method. Bulletin of the National Research Centre 43: 25. []
Abubakar, B. M. , Izham N. H. M., Salleh F. M., Omar M. S. S., and Wagiran A.. 2018. Comparison of different DNA extraction methods from leaves and roots of Eurycoma longifolia plant. Advanced Science Letters 24: 3641–3645. []
Aljanabi, S. M. , and Martinez I.. 1997. Universal and rapid salt‐extraction of high quality genomic DNA for PCR‐based techniques. Nucleic Acids Research 25: 4692–4693. [DOI] [PMC free article] [PubMed] []
Aljanabi, S. M. , Forget L., and Dookun A.. 1999. An improved and rapid protocol for the isolation of polysaccharide‐and polyphenol‐free sugarcane DNA. Plant Molecular Biology Reporter 17: 281–282. []
Arruda, S. , Pereira D., Silva‐Castro M., Brito M., and Waldschmidt A.. 2017. An optimized protocol for DNA extraction in plants with a high content of secondary metabolites, based on leaves of Mimosa tenuiflora (Willd.) Poir. (Leguminosae). Genetics and Molecular Research 16: 16039063. [DOI] [PubMed] []
Baird, N. A. , Etter P. D., Atwood T. S., Currey M. C., Shiver A. L., Lewis Z. A., Selker E. U., et al. 2008. Rapid SNP discovery and genetic mapping using sequenced RAD markers. PLoS ONE 3: e3376. [DOI] [PMC free article] [PubMed] []
Becklund, L. E. , and Ayers T. J.. 2022. The phylogeny of Errazurizia (Fabaceae: Amorpheae) and description of the new monotypic genus Pictarena . Systematic Botany 47: 1012–1024. []
Bernardo, G. D. , Galderisi U., Cipollaro M., and Cascino A.. 2005. Methods to improve the yield and quality of DNA from dried and processed figs. Biotechnology Progress 21: 546–549. [DOI] [PubMed] [Google Scholar]
Brewer, G. E. , Clarkson J. J., Maurin O., Zuntini A. R., Barber V., Bellot S., Biggs N., et al. 2019. Factors affecting targeted sequencing of 353 nuclear genes from herbarium specimens spanning the diversity of angiosperms. Frontiers in Plant Science 10: 1102. [DOI] [PMC free article] [PubMed] [Google Scholar]
Bult, C. , Källersjö M., and Suh Y.. 1992. Amplification and sequencing of 16/18S rDNA from gel‐purified total plant DNA. Plant Molecular Biology Reporter 10: 273–284. [Google Scholar]
Carey, S. J. , Becklund L. E., Fabre P. P., and Schenk J. J.. 2023. Optimizing the lysis step in CTAB DNA extractions of silica‐dried and herbarium leaf tissues. Applications in Plant Sciences 11(3): e11522. [DOI] [PMC free article] [PubMed] [Google Scholar]
Cerda, G. Y. D. L. , Landis J. B., Eifler E., Hernandez A. I., Li F.‐W., Zhang J., Tribble C. M., et al. 2023. Balancing read length and sequencing depth: optimizing Nanopore long‐read sequencing for monocots with an emphasis on Liliales. Applications in Plant Sciences 11(3): e11524. [DOI] [PMC free article] [PubMed] [Google Scholar]
Chase, M. W. , and Hills H. H.. 1991. Silica gel: An ideal material for field preservation of leaf samples for DNA studies. Taxon 40: 215–220. [Google Scholar]
Chen, C.‐Y. 2014. DNA polymerases drive DNA sequencing‐by‐synthesis technologies: Both past and present. Frontiers in Microbiology 5: 305. [DOI] [PMC free article] [PubMed] [Google Scholar]
Cohen, D. H. , and Schenk J. J.. 2022. Investigating phylogenetic placement and species‐level relationships in a recent radiation of Mentzelia section Bartonia (Loasaceae) from the Mojave Desert. Systematic Botany 47: 140–151. [Google Scholar]
Cota‐Sánchez, J. H. , Remarchuk K., and Ubayasena K.. 2006. Ready‐to‐use DNA extracted with a CTAB method adapted for herbarium specimens and mucilaginous plant tissue. Plant Molecular Biology Reporter 24: 161–167. [Google Scholar]
Couch, J. A. , and Fritz P. J.. 1990. Isolation of DNA from plants high in polyphenolics. Plant Molecular Biology Reporter 8: 8–12. [Google Scholar]
Csaikl, U. , Bastian H., Brettschneider R., Gauch S., Meir A., Schauerte M., Scholz F., et al. 1998. Comparative analysis of different DNA extraction protocols: A fast, universal maxi‐preparation of high quality plant DNA for genetic evaluation and phylogenetic studies. Plant Molecular Biology Reporter 16: 69–86. [Google Scholar]
Cullings, K. 1992. Design and testing of a plant‐specific PCR primer for ecological and evolutionary studies. Molecular Ecology 1: 233–240. [Google Scholar]
Davey, J. W. , and Blaxter M. L.. 2010. RADSeq: Next‐generation population genetics. Briefings in Functional Genomics 9: 416–423. [DOI] [PMC free article] [PubMed] [Google Scholar]
Dellaporta, S. L. , Wood J., and Hicks J. B.. 1983. A plant DNA minipreparation: Version II. Plant Molecular Biology Reporter 1: 19–21. [Google Scholar]
Demeke, T. , and Adams R.. 1992. The effects of plant polysaccharides and buffer additives on PCR. Biotechniques 12: 332–334. [PubMed] [Google Scholar]
Demeke, T. , and Jenkins G. R.. 2010. Influence of DNA extraction methods, PCR inhibitors and quantification methods on real‐time PCR assay of biotechnology‐derived traits. Analytical and Bioanalytical Chemistry 396: 1977–1990. [DOI] [PubMed] [Google Scholar]
Demeke, T. , Ratnayaka I., and Phan A.. 2009. Effects of DNA extraction and purification methods on real‐time quantitative PCR analysis of Roundup Ready soybean. Journal of AOAC International 92: 1136–1144. [PubMed] [Google Scholar]
Do, N. , and Adams R. P.. 1991. A simple technique for removing plant polysaccharides contaminants from DNA. Biotechniques 10: 162–164. [PubMed] [Google Scholar]
Donoghue, M. J. , Eaton D. A., Maya‐Lastra C. A., Landis M. J., Sweeney P. W., Olson M. E., Cacho N. I., et al. 2022. Replicated radiation of a plant clade along a cloud forest archipelago. Nature Ecology & Evolution 6: 1318–1329. [DOI] [PubMed] [Google Scholar]
Doyle, J. J. , and Doyle J. L.. 1987. A rapid DNA isolation procedure for small quantities of fresh leaf tissue. Phytochemical Bulletin 19: 11–15. [Google Scholar]
Doyle, J. J. , and Doyle J. L.. 1990. Isolation of plant DNA from fresh tissue. Focus 12: 13–15. [Google Scholar]
Doyle, J. J. , and Doyle J. L.. 2019. CATB isolation: The true story. Plant Science Bulletin 65: 15–18. [Google Scholar]
Drábková, L. , Kirschner J., and Vlček Č.. 2002. Comparison of seven DNA extraction and amplification protocols in historical herbarium specimens of Juncaceae. Plant Molecular Biology Reporter 20: 161–175. [Google Scholar]
Dutta, S. , Jones A., and Stacey M.. 1953. The separation of desoxypentosenucleic acids and pentosenucleic acids. Biochimica et Biophysica Acta 10: 613–622. [DOI] [PubMed] [Google Scholar]
El Maaiden, E. , El Kharrassi Y., Essamadi A. K., Moustaid K., and Nasser B.. 2019. Improved method for DNA extraction and purification from Tetrahymena pyriformis . Methods and Protocols 2: 40. [DOI] [PMC free article] [PubMed] [Google Scholar]
Esfandani‐Bozchaloyi, S. , Sheidai M., and Kalalegh M. H.. 2019. Comparison of DNA extraction methods from Geranium (Geraniaceae). Acta Botanica Hungarica 61: 251–266. [Google Scholar]
Fang, G. , Hammar S., and Grumet R.. 1992. A quick and inexpensive method for removing polysaccharides from plant genomic DNA. Biotechniques 13: 52–54. [PubMed] [Google Scholar]
Guillemaut, P. , and Maréchal‐Drouard L.. 1992. Isolation of plant DNA: A fast, inexpensive, and reliable method. Plant Molecular Biology Reporter 10: 60–65. [Google Scholar]
Hale, H. , Gardner E. M., Viruel J., Pokorny L., and Johnson M. G.. 2020. Strategies for reducing per‐sample costs in target capture sequencing for phylogenomics and population genomics in plants. Applications in Plant Sciences 8: e11337. [DOI] [PMC free article] [PubMed] [Google Scholar]
Hosaka, K. 2004. An easy, rapid, and inexpensive DNA extraction method, “One‐minute DNA extraction,” for PCR in potato. American Journal of Potato Research 81: 17–19. [Google Scholar]
Japelaghi, R. H. , Haddad R., and Garoosi G.‐A.. 2011. Rapid and efficient isolation of high quality nucleic acids from plant tissues rich in polyphenols and polysaccharides. Molecular Biotechnology 49: 129–137. [DOI] [PubMed] [Google Scholar]
Jobes, D. V. , Hurley D. L., and Thien L. B.. 1995. Plant DNA isolation: A method to efficiently remove polyphenolics, polysaccharides, and RNA. Taxon 44: 379–386. [Google Scholar]
John, M. E. 1992. An efficient method for isolation of RNA and DNA from plants containing polyphenolics. Nucleic Acids Research 20: 2381. [DOI] [PMC free article] [PubMed] [Google Scholar]
Johnson, G. , Canty S. W. J., Marck I. L., Wagner W., and Wen J.. 2023. Ethanol preservation and pretreatments facilitate quality DNA extractions in recalcitrant plant species. Applications in Plant Sciences 11(3): e11519. [DOI] [PMC free article] [PubMed] [Google Scholar]
Jones, M. M. , Nagalingum N. S., and Handley V. M.. 2023. Testing protocols to optimize DNA extraction from tough leaf tissue: A case study in Encephalartos . Applications in Plant Sciences 11(3): e11525. [DOI] [PMC free article] [PubMed] [Google Scholar]
Kang, M. , Chanderbali A., Lee S., Soltis D. E., Soltis P. S., and Kim S.. 2023. High‐molecular‐weight DNA extraction for long‐read sequencing of plant genomes: An optimization of standard methods. Applications in Plant Sciences 11(3): e11528. [DOI] [PMC free article] [PubMed] [Google Scholar]
Kasem, S. , Rice N., and Henry R.. 2008. DNA extraction from plant tissue. In Henry R. J. [ed.], Plant Genotyping II: SNP Technology, 219–271. Oxford University Press, New York, New York, USA. [Google Scholar]
Khanuja, S. P. , Shasany A. K., Darokar M. P., and Kumar S.. 1999. Rapid isolation of DNA from dry and fresh samples of plants producing large amounts of secondary metabolites and essential oils. Plant Molecular Biology Reporter 17: 1–7. [Google Scholar]
Kim, C. , Lee C., Shin J., Chung Y., and Hyung N.. 1997. A simple and rapid method for isolation of high quality genomic DNA from fruit trees and conifers using PVP. Nucleic Acids Research 25: 1085–1086. [DOI] [PMC free article] [PubMed] [Google Scholar]
Kistler, L. 2012. Ancient DNA extraction from plants. Methods in Molecular Biology 840: 71–79. [DOI] [PubMed] [Google Scholar]
Kotchoni, S. O. , Gachomo E. W., and Jimenez‐Lopez J. C.. 2011. A plant cocktail amenable for PCR‐based genetic analysis in Arabidopsis thaliana . Molecular Biology Reports 38: 5281–5284. [DOI] [PubMed] [Google Scholar]
Larridon, I. , Villaverde T., Zuntini A. R., Pokorny L., Brewer G. E., Epitawalage N., Fairlie I., et al. 2020. Tackling rapid radiations with targeted sequencing. Frontiers in Plant Science 10: 1655. [DOI] [PMC free article] [PubMed] [Google Scholar]
Leaché, A. D. , Banbury B. L., Felsenstein J., de Oca A. N. M., and Stamatakis A.. 2015. Short tree, long tree, right tree, wrong tree: New acquisition bias corrections for inferring SNP phylogenies. Systematic Biology 64: 1032–1047. [DOI] [PMC free article] [PubMed] [Google Scholar]
Li, H. , Luo J., Hemphill J. K., Wang J.‐T., and Gould J. H.. 2001. A rapid and high yielding DNA miniprep for cotton (Gossypium spp.). Plant Molecular Biology Reporter 19: 183. [Google Scholar]
Listyanto, H. , Muhammad I., Erfianti T., Herida A., Kusumaningrum H., Loka B., and Setyowati E.. 2021. DNA isolation of clove and lemongrass using modification of the Doyle and Doyle methods and their relation with antioxidant activity. Journal of Physics: Conference Series 1943: 012081. [Google Scholar]
Lodhi, M. A. , Ye G.‐N., Weeden N. F., and Reisch B. I.. 1994. A simple and efficient method for DNA extraction from grapevine cultivars and Vitis species. Plant Molecular Biology Reporter 12: 6–13. [Google Scholar]
Loomis, W. D. , and Battaile J.. 1966. Plant phenolic compounds and the isolation of plant enzymes. Phytochemistry 5: 423–438. [Google Scholar]
Maguire, T. L. , Collins G. G., and Sedgley M.. 1994. A modified CTAB DNA extraction procedure for plants belonging to the family Proteaceae. Plant Molecular Biology Reporter 12: 106–109. [Google Scholar]
Manen, J.‐F. , Sinitsyna O., Aeschbach L., Markov A. V., and Sinitsyn A.. 2005. A fully automatable enzymatic method for DNA extraction from plant tissues. BMC Plant Biology 5: 23. [DOI] [PMC free article] [PubMed] [Google Scholar]
Michiels, A. , Van den Ende W., Tucker M., Van Riet L., and Van Laere A.. 2003. Extraction of high‐quality genomic DNA from latex‐containing plants. Analytical Biochemistry 315: 85–89. [DOI] [PubMed] [Google Scholar]
Moreira, P. , and Oliveira D.. 2011. Leaf age affects the quality of DNA extracted from Dimorphandra mollis (Fabaceae), a tropical tree species from the Cerrado region of Brazil. Genetics and Molecular Research 10: 353–358. [DOI] [PubMed] [Google Scholar]
Murray, M. , and Thompson W.. 1980. Rapid isolation of high molecular weight plant DNA. Nucleic Acids Research 8: 4321–4326. [DOI] [PMC free article] [PubMed] [Google Scholar]
Nazhad, N. R. , and Solouki M.. 2008. Separation of DNA for molecular markers analysis from leaves of the Vitis vinifera . Pakistan Journal of Biological Sciences 11: 1436–1442. [DOI] [PubMed] [Google Scholar]
Pandey, R. N. , Adams R. P., and Flournoy L. E.. 1996. Inhibition of random amplified polymorphic DNAs (RAPDs) by plant polysaccharides. Plant Molecular Biology Reporter 14: 17–22. [Google Scholar]
Pirttilä, A. M. , Hirsikorpi M., Kämäräinen T., Jaakola L., and Hohtola A.. 2001. DNA isolation methods for medicinal and aromatic plants. Plant Molecular Biology Reporter 19: 273. [Google Scholar]
Porebski, S. , Bailey L. G., and Baum B. R.. 1997. Modification of a CTAB DNA extraction protocol for plants containing high polysaccharide and polyphenol components. Plant Molecular Biology Reporter 15: 8–15. [Google Scholar]
Pratyusha, S. 2022. Phenolic compounds in the plant development and defense: An overview. In Hasanuzzaman M. and Nahar K. [eds.], Plant Stress Physiology: Perspectives in Agriculture. IntechOpen, London, United Kingdom. [Google Scholar]
Puchooa, D. 2004. A simple, rapid and efficient method for the extraction of genomic DNA from lychee (Litchi chinensis Sonn.). African Journal of Biotechnology 3: 253–255. [Google Scholar]
Ramachandran, R. , Vishnu B., Gangaprasad A., and Siril E.. 2022. Effective and reliable protocol for DNA isolation from polyphenolic leaves and fruits of Garcinia gummi‐gutta (L.) Robs. Proceedings of the National Academy of Sciences, India Section B: Biological Sciences 92: 825–831. [Google Scholar]
Ribeiro, R. , and Lovato M.. 2007. Comparative analysis of different DNA extraction protocols in fresh and herbarium specimens of the genus Dalbergia . Genetics and Molecular Research 6: 173–187. [PubMed] [Google Scholar]
Rogers, S. O. , and Bendich A. J.. 1985. Extraction of DNA from milligram amounts of fresh, herbarium and mummified plant tissues. Plant Molecular Biology 5: 69–76. [DOI] [PubMed] [Google Scholar]
Rogstad, S. H. 1992. Saturated NaCl‐CTAB solution as a means of field preservation of leaves for DNA analyses. Taxon 41: 701–708. [Google Scholar]
Saghai‐Maroof, M. A. , Soliman K. M., Jorgensen R. A., and Allard R. W.. 1984. Ribosomal DNA spacer‐length polymorphisms in barley: Mendelian inheritance, chromosomal location, and population dynamics. Proceedings of the National Academy of Sciences, USA 81: 8014–8018. [DOI] [PMC free article] [PubMed] [Google Scholar]
Sahu, S. K. , Thangaraj M., and Kathiresan K.. 2012. DNA extraction protocol for plants with high levels of secondary metabolites and polysaccharides without using liquid nitrogen and phenol. International Scholarly Research Notices 2012: 205049. [DOI] [PMC free article] [PubMed] [Google Scholar]
Schenk, J. J. , and Hufford L.. 2011. Phylogeny and taxonomy of Mentzelia section Bartonia (Loasaceae). Systematic Botany 36: 711–720. [Google Scholar]
Scobeyeva, V. , Omelchenko D., Dyakov L., Konovalov A., Speranskaya A., and Krinitsina A.. 2018. Comparison of some plant DNA extraction methods. Russian Journal of Genetics 54: 576–586. [Google Scholar]
Scott, K. D. , and Playford J.. 1996. DNA extraction technique for PCR in rain forest plant species. Biotechniques 20: 974–978. [DOI] [PubMed] [Google Scholar]
Sharma, A. D. , Gill P. K., and Singh P.. 2002. DNA isolation from dry and fresh samples of polysaccharide‐rich plants. Plant Molecular Biology Reporter 20: 415. [Google Scholar]
Sharma, K. K. , Lavanya M., and Anjaiah V.. 2000. A method for isolation and purification of peanut genomic DNA suitable for analytical applications. Plant Molecular Biology Reporter 18: 393. [Google Scholar]
Shioda, M. , and Murakami‐Murofushi K.. 1987. Selective inhibition of DNA polymerase α by a polysaccharide purified from slime of Physarumpolycephalum . Biochemical and Biophysical Research Communications 146: 61–66. [DOI] [PubMed] [Google Scholar]
Silva, M. N. d. 2010. Extraction of genomic DNA from leaf tissues of mature native species of the Cerrado. Revista Árvore 34: 973–978. [Google Scholar]
Staats, M. , Cuenca A., Richardson J. E., Vrielink‐van Ginkel R., Petersen G., Seberg O., and Bakker F. T.. 2011. DNA damage in plant herbarium tissue. PLoS ONE 6: e28448. [DOI] [PMC free article] [PubMed] [Google Scholar]
Stein, D. B. 1993. Isolation and comparison of nucleic acids from land plants: Nuclear and organellar genes. Methods in Enzymology 224: 153–167. [DOI] [PubMed] [Google Scholar]
Štorchová, H. , Hrdličková R., Chrtek J. Jr., Tetera M., Fitze D., and Fehrer J.. 2000. An improved method of DNA isolation from plants collected in the field and conserved in saturated NaCl/CTAB solution. Taxon 49: 79–84. [Google Scholar]
Syamkumar, S. , Lowarence B., and Sasikumar B.. 2003. Isolation and amplification of DNA from rhizomes of turmeric and ginger. Plant Molecular Biology Reporter 21: 171. [Google Scholar]
Tel‐Zur, N. , Abbo S., Myslabodski D., and Mizrahi Y.. 1999. Modified CTAB procedure for DNA isolation from epiphytic cacti of the genera Hylocereus and Selenicereus (Cactaceae). Plant Molecular Biology Reporter 17: 249–254. [Google Scholar]
Usha Rani, P. , and Jyothsna Y.. 2010. Biochemical and enzymatic changes in rice plants as a mechanism of defense. Acta Physiologiae Plantarum 32: 695–701. [Google Scholar]
Varma, A. , Padh H., and Shrivastava N.. 2007. Plant genomic DNA isolation: An art or a science. Biotechnology Journal: Healthcare Nutrition Technology 2: 386–392. [DOI] [PubMed] [Google Scholar]
Wilkie, S. E. , Isaac P. G., and Slater R. J.. 1993. Random amplified polymorphic DNA (RAPD) markers for genetic analysis in Allium . Theoretical and Applied Genetics 86: 497–504. [DOI] [PubMed] [Google Scholar]
Wilson, I. G. 1997. Inhibition and facilitation of nucleic acid amplification. Applied and Environmental Microbiology 63: 3741–3751. [DOI] [PMC free article] [PubMed] [Google Scholar]
Xie, P.‐J. , Ke Y.‐T., and Kuo L.‐Y.. 2023. Modified CTAB protocols for high‐molecular‐weight DNA extractions from ferns. Applications in Plant Sciences 11(3): e11526. [DOI] [PMC free article] [PubMed] [Google Scholar]
Xin, Z. , and Chen J.. 2012. A high throughput DNA extraction method with high yield and quality. Plant Methods 8: 26. [DOI] [PMC free article] [PubMed] [Google Scholar]
Zamboni, A. , Pierantoni L., and De Franceschi P.. 2008. Total RNA extraction from strawberry tree (Arbutus unedo) and several other woody‐plants. iForest ‐ Biogeosciences and Forestry 1: 122–125. [Google Scholar]
Associated Data

This section collects any data citations, data availability statements, or supplementary materials included in this article.

Supplementary Materials

Appendix S1. Total genomic DNA extraction from plant tissue using CTAB.

Appendix S2. Total genomic DNA extraction from plant tissue using CTAB + PVP.

Appendix S3. Total genomic DNA extraction from plant tissue using CTAB + SDS.

Appendix S4. Total genomic DNA extraction from plant tissue using CTAB + sorbitol.

Articles from Applications in Plant Sciences are provided here courtesy of Wiley
